#!/usr/bin/perl
# gen_cmp.pl -- generate the storage compare list of the z80 A/B bench from the die model.
#   usage: perl gen_cmp.pl ../../rtl/nuked-md/z80.v z80_cmp.svh
# Scans module z80cpu of z80.v for
#   - the z80_dlatch / z80_rs_trig_nor / z80_rs_trig_nand instances (register outp, or q and nq)
#   - every `reg` declaration (the inline registers, incl. the regs/regs2 arrays, every element)
# and writes an include with the packed vectors sto_a (die, hierarchical <inst>.<reg>) / sto_b
# (rtl, <inst>_<reg>) and the per-signal report task, so that the bench compares every storage
# bit of both models and names the first one that differs.
use strict; use warnings;
my ($in, $out) = @ARGV;
open(my $fh, '<', $in) or die "$in: $!"; local $/; my $src = <$fh>; close $fh;
$src =~ s/\r\n/\n/g;
$src =~ /(module z80cpu\b.*?\nendmodule\n)/s or die "no z80cpu module";
my $body = $1;

my @items;   # [name, die_ref, rtl_ref, width]
my %cnt = (dl => 0, nor => 0, nand => 0, inl => 0);
my $bits = 0;
for my $line (split /\n/, $body) {
	if ($line =~ /^\t(z80_dlatch|z80_rs_trig_nor|z80_rs_trig_nand)\s+(\w+)\s*$/) {
		my ($kind, $name) = ($1, $2);
		if ($kind eq 'z80_dlatch') {
			$cnt{dl}++;
			push @items, ["$name.outp", "u_die.$name.outp", "u_rtl.${name}_outp", 1];
		} else {
			$cnt{$kind eq 'z80_rs_trig_nor' ? 'nor' : 'nand'}++;
			push @items, ["$name.q", "u_die.$name.q", "u_rtl.${name}_q", 1];
			push @items, ["$name.nq", "u_die.$name.nq", "u_rtl.${name}_nq", 1];
		}
	} elsif ($line =~ /^\treg\s+(?:\[(\d+):(\d+)\]\s*)?(.*);/) {
		my ($hi, $lo, $rest) = ($1, $2, $3);
		my $w = defined $hi ? $hi - $lo + 1 : 1;
		$rest =~ s{//.*}{};
		for my $d (split /,/, $rest) {
			$d =~ s/\s+//g;
			$d =~ s/=.*//;
			if ($d =~ /^(\w+)\[(\d+):(\d+)\]\[(\d+):(\d+)\]$/) {
				my ($n, $a1, $a0, $b1, $b0) = ($1, $2, $3, $4, $5);
				for my $i ($a0 .. $a1) { for my $j ($b0 .. $b1) {
					$cnt{inl}++;
					push @items, ["$n\[$i\]\[$j\]", "u_die.$n\[$i\]\[$j\]", "u_rtl.$n\[$i\]\[$j\]", $w];
				} }
			} elsif ($d =~ /^(\w+)$/) {
				$cnt{inl}++;
				push @items, [$1, "u_die.$1", "u_rtl.$1", $w];
			} else { die "cannot parse reg declaration: $line" }
		}
	}
}
$bits += $_->[3] for @items;

open($fh, '>', $out) or die "$out: $!";
binmode $fh;
print $fh "// generated by gen_cmp.pl from $in -- do not edit\n";
print $fh "// $cnt{dl} z80_dlatch (outp), $cnt{nor} z80_rs_trig_nor + $cnt{nand} z80_rs_trig_nand (q, nq), $cnt{inl} inline registers/array elements: $bits bits\n";
print $fh "localparam STO_BITS = $bits;\n";
print $fh "wire [STO_BITS-1:0] sto_a = {\n" . join(",\n", map { "\t$_->[1]" } @items) . "};\n";
print $fh "wire [STO_BITS-1:0] sto_b = {\n" . join(",\n", map { "\t$_->[2]" } @items) . "};\n";
print $fh "task automatic report_storage(input string phase);\n";
print $fh "\t`CMP(\"$_->[0]\", $_->[1], $_->[2])\n" for @items;
print $fh "endtask\n";
close $fh;
print STDERR "gen_cmp: $cnt{dl} dlatch, $cnt{nor} rs_nor, $cnt{nand} rs_nand, $cnt{inl} inline regs, $bits storage bits\n";
