// z80 A/B equivalence bench: die model `z80cpu` (rtl/nuked-md/z80.v) against the 1:1
// synthesis-friendly `z80cpu_rtl` (rtl/nuked-md/z80_rtl.v). Identical stimulus into both;
// every output pin and EVERY storage element (899 bits, list generated by gen_cmp.pl into
// z80_cmp.svh) compared twice per MCLK cycle:
//   - at posedge MCLK, before the non-blocking updates land (the values the flops sample)
//   - a quarter period after posedge (the values produced by that edge, inputs unchanged)
// Stimulus is applied at negedge MCLK only. First mismatch prints cycle/signal/values and
// stops the run with FAIL.
//
// CLK (= ZCLK, the Z80 clock) is carried into both models as data exactly as on md_board;
// here it is the real 16-high / 14-low shape (period 30 MCLK2 = MCLK2/30). Both models get
// the identical CLK, so its exact shape does not affect the equivalence proof, only coverage.
//
// Memory / bus model (a plain, shared, reference-driven interface -- the die model, as the
// reference, forms DATA_i and the write data for BOTH models, so the two always see a
// bit-identical input stream; any divergence in an rtl output is caught by the output CMP
// before it could reach the shared memory). Active-low MREQ/IORQ/RD/WR/M1 as on the die.
//   0000-1FFF  ROM (z80_rom.hex, the directed program)     )
//   2000-3FFF  RAM                                          ) one flat 64 KB array; the
//   4000-7FFF  peripheral region (bridge-style WAIT)        ) whole space is read/write so
//   8000-FFFF  68000 window       (bridge-style WAIT)       ) random code can run anywhere
//   IN  (IORQ&RD)         -> stub port = low address byte
//   INT ACK (M1&IORQ)     -> int_vec (RST byte for IM0 / vector byte for IM2)
`timescale 1ps/1ps
module tb_z80;

// MCLK 107.38635 MHz (md_board MCLK2), same as the tmss/ym benches
reg MCLK = 0;
always #4656 MCLK = ~MCLK;        // 9.312 ns

// ---------------------------------------------------------------- shared inputs
reg  [7:0] DATA_i_drv;             // driven combinationally below
reg        CLK = 1'b0;             // ZCLK
reg        WAIT = 1'b0;
reg        INT = 1'b0;
reg        NMI = 1'b0;
reg        RESET = 1'b0;           // active low (0 = reset asserted)
reg        BUSRQ = 1'b1;           // active low (0 = request)
reg  [7:0] int_vec = 8'hFF;        // interrupt-acknowledge byte (RST 38h by default)

// ---------------------------------------------------------------- outputs A (die) / B (rtl)
wire [15:0] ADDRESS_a, ADDRESS_b;
wire        ADDRESS_z_a, ADDRESS_z_b;
wire [7:0]  DATA_o_a, DATA_o_b;
wire        DATA_z_a, DATA_z_b;
wire        M1_a, M1_b, MREQ_a, MREQ_b, MREQ_z_a, MREQ_z_b;
wire        IORQ_a, IORQ_b, IORQ_z_a, IORQ_z_b;
wire        RD_a, RD_b, RD_z_a, RD_z_b, WR_a, WR_b, WR_z_a, WR_z_b;
wire        RFSH_a, RFSH_b, HALT_a, HALT_b, BUSAK_a, BUSAK_b;

z80cpu u_die (
	.MCLK(MCLK), .CLK(CLK),
	.ADDRESS(ADDRESS_a), .ADDRESS_z(ADDRESS_z_a),
	.DATA_i(DATA_i_drv), .DATA_o(DATA_o_a), .DATA_z(DATA_z_a),
	.M1(M1_a), .MREQ(MREQ_a), .MREQ_z(MREQ_z_a), .IORQ(IORQ_a), .IORQ_z(IORQ_z_a),
	.RD(RD_a), .RD_z(RD_z_a), .WR(WR_a), .WR_z(WR_z_a), .RFSH(RFSH_a), .HALT(HALT_a),
	.WAIT(WAIT), .INT(INT), .NMI(NMI), .RESET(RESET), .BUSRQ(BUSRQ), .BUSAK(BUSAK_a));

z80cpu_rtl u_rtl (
	.MCLK(MCLK), .CLK(CLK),
	.ADDRESS(ADDRESS_b), .ADDRESS_z(ADDRESS_z_b),
	.DATA_i(DATA_i_drv), .DATA_o(DATA_o_b), .DATA_z(DATA_z_b),
	.M1(M1_b), .MREQ(MREQ_b), .MREQ_z(MREQ_z_b), .IORQ(IORQ_b), .IORQ_z(IORQ_z_b),
	.RD(RD_b), .RD_z(RD_z_b), .WR(WR_b), .WR_z(WR_z_b), .RFSH(RFSH_b), .HALT(HALT_b),
	.WAIT(WAIT), .INT(INT), .NMI(NMI), .RESET(RESET), .BUSRQ(BUSRQ), .BUSAK(BUSAK_b));

// ---------------------------------------------------------------- shared memory (64 KB)
reg [7:0] mem [0:65535];
// reference-driven: address / control / write data all come from the die model
wire [15:0] a      = ADDRESS_a;
wire        mreq_n = MREQ_a;       // active low
wire        iorq_n = IORQ_a;
wire        wr_n   = WR_a;
wire        m1_n   = M1_a;         // active low

// asynchronous read: interrupt-ack vector, else IN stub, else memory
always @(*) begin
	if (~m1_n & ~iorq_n)      DATA_i_drv = int_vec;   // interrupt acknowledge
	else if (~iorq_n)         DATA_i_drv = a[7:0];    // IN (C)/(n) stub port
	else                      DATA_i_drv = mem[a];    // memory read
end
// memory write (MREQ & WR both low); OUT (IORQ) is ignored
always @(posedge MCLK)
	if (~mreq_n & ~wr_n) mem[a] <= DATA_o_a;

// ---------------------------------------------------------------- ZCLK (16 high / 14 low)
integer zcnt = 0;
always @(negedge MCLK) begin
	zcnt = (zcnt == 29) ? 0 : zcnt + 1;
	CLK  = (zcnt < 16);
end

// ---------------------------------------------------------------- comparator
integer cycle = 0;                // MCLK edges seen
integer ncmp  = 0;                // compare points (2 per cycle)
integer nmis  = 0;
reg     xcheck_en = 0;            // after the first reset: no X allowed on an output
reg     rand_phase = 0;
string  phase;

`define CMP(NAME, A, B) \
	if ((A) !== (B)) begin \
		$display("MISMATCH cycle %0d t=%0t (%s) %s: die=%h rtl=%h", cycle, $time, phase, NAME, A, B); \
		nmis = nmis + 1; \
	end

// every output pin, packed for a fast X-check
wire [40:0] outs_a = {ADDRESS_a, ADDRESS_z_a, DATA_o_a, DATA_z_a, M1_a, MREQ_a, MREQ_z_a,
	IORQ_a, IORQ_z_a, RD_a, RD_z_a, WR_a, WR_z_a, RFSH_a, HALT_a, BUSAK_a};
wire [40:0] outs_b = {ADDRESS_b, ADDRESS_z_b, DATA_o_b, DATA_z_b, M1_b, MREQ_b, MREQ_z_b,
	IORQ_b, IORQ_z_b, RD_b, RD_z_b, WR_b, WR_z_b, RFSH_b, HALT_b, BUSAK_b};

// storage compare list (899 bits) + report_storage(phase) task
`include "z80_cmp.svh"

task automatic check(input string ph);
	phase = ph;
	ncmp = ncmp + 1;
	// every output pin
	`CMP("ADDRESS",   ADDRESS_a,   ADDRESS_b)
	`CMP("ADDRESS_z", ADDRESS_z_a, ADDRESS_z_b)
	`CMP("DATA_o",    DATA_o_a,    DATA_o_b)
	`CMP("DATA_z",    DATA_z_a,    DATA_z_b)
	`CMP("M1",        M1_a,        M1_b)
	`CMP("MREQ",      MREQ_a,      MREQ_b)
	`CMP("MREQ_z",    MREQ_z_a,    MREQ_z_b)
	`CMP("IORQ",      IORQ_a,      IORQ_b)
	`CMP("IORQ_z",    IORQ_z_a,    IORQ_z_b)
	`CMP("RD",        RD_a,        RD_b)
	`CMP("RD_z",      RD_z_a,      RD_z_b)
	`CMP("WR",        WR_a,        WR_b)
	`CMP("WR_z",      WR_z_a,      WR_z_b)
	`CMP("RFSH",      RFSH_a,      RFSH_b)
	`CMP("HALT",      HALT_a,      HALT_b)
	`CMP("BUSAK",     BUSAK_a,     BUSAK_b)
	// every storage element (hierarchical die vs inline rtl)
	report_storage(ph);
	// after the first reset nothing may be X on an output pin
	if (xcheck_en && ($isunknown(outs_a) || $isunknown(outs_b))) begin
		$display("MISMATCH cycle %0d t=%0t (%s) X on an output: die=%b rtl=%b", cycle, $time, ph, outs_a, outs_b);
		nmis = nmis + 1;
	end
	if (nmis != 0) begin
		$display("FAIL after %0d cycles (%0d compare points): %0d mismatch(es)", cycle, ncmp, nmis);
		$finish;
	end
endtask

// The die model's z80_rs_trig_* use BLOCKING assignments, so their q/nq settle in the
// active region of the posedge (not the NBA region like the dlatch/inline registers and the
// whole rtl). A compare taken exactly at the posedge would therefore read the die's rs bits
// already updated but the rtl's not yet -- a scheduling artifact, not a difference. Both
// models are instead compared at two *settled* quarter points per MCLK, where the die
// (blocking rs done, NBA done) and the rtl (all NBA done) have both fully resolved:
//   - a quarter period after posedge  (state produced by that edge, CLK still in its high half)
//   - a quarter period after negedge  (same registers, combinational logic re-settled with CLK
//                                      in its low half and the async inputs applied at negedge)
// Registers change only on posedge in both models, so the post-edge point catches every storage
// divergence within a quarter cycle; the post-negedge point adds the CLK-low combinational phase.
always @(posedge MCLK) begin
	cycle = cycle + 1;
	#2328 check("post-edge");
end
always @(negedge MCLK) begin
	#2328 check("post-negedge");
end

// ---------------------------------------------------------------- stimulus helpers
task automatic tick(input integer n);
	repeat (n) @(negedge MCLK);
endtask

// ---------------------------------------------------------------- async event side process
// Constrained-random perturbation of the asynchronous pins. Enabled in both phases; in the
// directed phase it is light (so the program makes progress); in the random phase it is heavy.
integer ev_i;
initial begin
	@(negedge MCLK);
	forever begin
		@(negedge MCLK);
		if (rand_phase) begin
			if ($urandom_range(0,99) < 25) WAIT  = $urandom_range(0,1);
			if ($urandom_range(0,99) < 12) INT   = $urandom_range(0,1);
			if ($urandom_range(0,99) < 6)  NMI   = $urandom_range(0,1);
			if ($urandom_range(0,99) < 8)  BUSRQ = $urandom_range(0,1);
			if ($urandom_range(0,999) < 3) begin        // occasional async reset pulse
				RESET = 0; tick($urandom_range(1,50)); RESET = 1;
			end
			if ($urandom_range(0,999) < 2) int_vec = $urandom;   // vary the ack byte
		end else begin
			// light WAIT correlated with the peripheral / 68000 window (bridge-style)
			if (a >= 16'h4000 && (~mreq_n | ~iorq_n))
				WAIT = ($urandom_range(0,3) != 0);
			else
				WAIT = 0;
		end
	end
end

// ---------------------------------------------------------------- main
integer seed;
integer n_random;
integer base;
integer k;
initial begin
	if (!$value$plusargs("SEED=%d", seed)) seed = 1;
	if (!$value$plusargs("NRAND=%d", n_random)) n_random = 1200000;
	void'($urandom(seed));

	// defined memory everywhere, then the directed ROM over 0000-1FFF
	for (k = 0; k < 65536; k = k + 1) mem[k] = 8'h00;
	$readmemh("z80_rom.hex", mem);
	$display("tb_z80: seed=%0d random cycles>=%0d", seed, n_random);

	// ================= directed phase =================
	// power-up reset
	RESET = 0; INT = 0; NMI = 0; BUSRQ = 1; WAIT = 0; int_vec = 8'hFF;
	tick(200);
	RESET = 1;                       // release: program starts
	tick(60);
	xcheck_en = 1;

	// let the instruction-family walk run
	tick(40000);

	// INT (IM 1 by default in the program's DI/EI dance): assert for a couple of ZCLK
	INT = 1; tick(900); INT = 0; tick(4000);
	// NMI edge
	NMI = 1; tick(200); NMI = 0; tick(4000);
	// a few more interrupt / nmi pulses interleaved with running
	for (k = 0; k < 6; k = k + 1) begin
		INT = 1; tick(700); INT = 0; tick(3000);
		if (k % 2 == 0) begin NMI = 1; tick(150); NMI = 0; tick(2500); end
	end

	// IM 0 style: supply an RST byte on the ack
	int_vec = 8'hFF; INT = 1; tick(1200); INT = 0; tick(4000);
	// IM 2 style vector byte
	int_vec = 8'h0A; INT = 1; tick(1200); INT = 0; tick(4000);
	int_vec = 8'hFF;

	// BUSRQ: take the bus mid-execution, hold, release
	BUSRQ = 0; tick(1500); BUSRQ = 1; tick(3000);
	// BUSRQ taken right in the middle of a bus cycle (short pulses)
	for (k = 0; k < 4; k = k + 1) begin BUSRQ = 0; tick($urandom_range(20,300)); BUSRQ = 1; tick($urandom_range(200,1200)); end

	// WAIT insertion bursts (bridge style)
	for (k = 0; k < 8; k = k + 1) begin WAIT = 1; tick($urandom_range(15,120)); WAIT = 0; tick($urandom_range(200,900)); end

	// RESET mid-instruction, then continue
	tick(3000);
	RESET = 0; tick(40); RESET = 1; tick(5000);
	RESET = 0; tick(9);  RESET = 1; tick(5000);   // very short reset pulse
	tick(20000);
	$display("INFO directed phase done at cycle %0d (nmis=%0d)", cycle, nmis);

	// ================= random phase =================
	// fill the whole 64 KB with random bytes: the CPU now executes random memory as code
	for (k = 0; k < 65536; k = k + 1) mem[k] = $urandom;
	base = cycle;
	rand_phase = 1;
	while (cycle < base + n_random) tick(200);
	rand_phase = 0;
	WAIT = 0; INT = 0; NMI = 0; BUSRQ = 1; RESET = 1;
	tick(20);

	$display("PASS: %0d MCLK cycles, %0d compare points, %0d storage bits/point, %0d mismatches",
		cycle, ncmp, STO_BITS, nmis);
	$finish;
end

initial begin repeat (4000000) @(posedge MCLK); $display("TIMEOUT cycle=%0d", cycle); $finish; end

endmodule
