// generated by gen_cmp.pl from C:/Users/joelw/Documents/MegaCD_MiSTer_New/MegaCD_MiSTer-master/rtl/nuked-md/z80.v -- do not edit
// 128 z80_dlatch (outp), 34 z80_rs_trig_nor + 18 z80_rs_trig_nand (q, nq), 73 inline registers/array elements: 899 bits
localparam STO_BITS = 899;
wire [STO_BITS-1:0] sto_a = {
	u_die.w9,
	u_die.w30,
	u_die.w40,
	u_die.w40_i,
	u_die.w73,
	u_die.w74,
	u_die.w78_i,
	u_die.w80,
	u_die.w92,
	u_die.w95_i,
	u_die.w100,
	u_die.w145,
	u_die.w146,
	u_die.w147_prev,
	u_die.w302,
	u_die.w304_r,
	u_die.w320,
	u_die.w327,
	u_die.w329_r,
	u_die.w331_r,
	u_die.w392,
	u_die.w420,
	u_die.w425,
	u_die.w441,
	u_die.w445,
	u_die.w450,
	u_die.w464,
	u_die.w473,
	u_die.w476,
	u_die.w484,
	u_die.w496,
	u_die.w498,
	u_die.w499,
	u_die.w503,
	u_die.w510,
	u_die.w511,
	u_die.w513,
	u_die.regs[0][0],
	u_die.regs[0][1],
	u_die.regs[1][0],
	u_die.regs[1][1],
	u_die.regs[2][0],
	u_die.regs[2][1],
	u_die.regs[3][0],
	u_die.regs[3][1],
	u_die.regs[4][0],
	u_die.regs[4][1],
	u_die.regs[5][0],
	u_die.regs[5][1],
	u_die.regs[6][0],
	u_die.regs[6][1],
	u_die.regs[7][0],
	u_die.regs[7][1],
	u_die.regs[8][0],
	u_die.regs[8][1],
	u_die.regs[9][0],
	u_die.regs[9][1],
	u_die.regs[10][0],
	u_die.regs[10][1],
	u_die.regs[11][0],
	u_die.regs[11][1],
	u_die.regs2[0][0],
	u_die.regs2[0][1],
	u_die.regs2[1][0],
	u_die.regs2[1][1],
	u_die.w514,
	u_die.w515,
	u_die.w520,
	u_die.w521,
	u_die.w522,
	u_die.w524,
	u_die.w526,
	u_die.w527,
	u_die.rs1.q,
	u_die.rs1.nq,
	u_die.dl1.outp,
	u_die.rs2.q,
	u_die.rs2.nq,
	u_die.rs4.q,
	u_die.rs4.nq,
	u_die.rs5.q,
	u_die.rs5.nq,
	u_die.dl2.outp,
	u_die.rs7.q,
	u_die.rs7.nq,
	u_die.rs6.q,
	u_die.rs6.nq,
	u_die.rs8.q,
	u_die.rs8.nq,
	u_die.rs9.q,
	u_die.rs9.nq,
	u_die.dl3.outp,
	u_die.dl4.outp,
	u_die.rs18.q,
	u_die.rs18.nq,
	u_die.rs19.q,
	u_die.rs19.nq,
	u_die.rs21.q,
	u_die.rs21.nq,
	u_die.rs22.q,
	u_die.rs22.nq,
	u_die.dl5.outp,
	u_die.dl6.outp,
	u_die.dl7.outp,
	u_die.dl8.outp,
	u_die.rs31.q,
	u_die.rs31.nq,
	u_die.dl9.outp,
	u_die.rs33.q,
	u_die.rs33.nq,
	u_die.dl10.outp,
	u_die.dl11.outp,
	u_die.rs34.q,
	u_die.rs34.nq,
	u_die.dl12.outp,
	u_die.dl82.outp,
	u_die.rs37.q,
	u_die.rs37.nq,
	u_die.dl_w38.outp,
	u_die.rs39.q,
	u_die.rs39.nq,
	u_die.dl13.outp,
	u_die.rs44.q,
	u_die.rs44.nq,
	u_die.dl14.outp,
	u_die.dl15.outp,
	u_die.dl16.outp,
	u_die.dl17.outp,
	u_die.dl18.outp,
	u_die.rs48.q,
	u_die.rs48.nq,
	u_die.rs50.q,
	u_die.rs50.nq,
	u_die.rs51.q,
	u_die.rs51.nq,
	u_die.dl19.outp,
	u_die.dl20.outp,
	u_die.rs54.q,
	u_die.rs54.nq,
	u_die.rs56.q,
	u_die.rs56.nq,
	u_die.rs58.q,
	u_die.rs58.nq,
	u_die.rs59.q,
	u_die.rs59.nq,
	u_die.dl21.outp,
	u_die.rs61.q,
	u_die.rs61.nq,
	u_die.dl22.outp,
	u_die.dl23.outp,
	u_die.rs63.q,
	u_die.rs63.nq,
	u_die.dl24.outp,
	u_die.rs66.q,
	u_die.rs66.nq,
	u_die.dl25.outp,
	u_die.rs68.q,
	u_die.rs68.nq,
	u_die.dl26.outp,
	u_die.dl27.outp,
	u_die.dl28.outp,
	u_die.dl43.outp,
	u_die.dw98.outp,
	u_die.dw99.outp,
	u_die.dl29.outp,
	u_die.dw104.outp,
	u_die.dw107.outp,
	u_die.dl30.outp,
	u_die.rs109.q,
	u_die.rs109.nq,
	u_die.rs111.q,
	u_die.rs111.nq,
	u_die.dw112.outp,
	u_die.dl31.outp,
	u_die.rs114.q,
	u_die.rs114.nq,
	u_die.rs115.q,
	u_die.rs115.nq,
	u_die.dl32.outp,
	u_die.rs120.q,
	u_die.rs120.nq,
	u_die.rs121.q,
	u_die.rs121.nq,
	u_die.dl33.outp,
	u_die.rs123.q,
	u_die.rs123.nq,
	u_die.dl34.outp,
	u_die.rs127.q,
	u_die.rs127.nq,
	u_die.dl35.outp,
	u_die.rsrfsh.q,
	u_die.rsrfsh.nq,
	u_die.dw130.outp,
	u_die.rs131.q,
	u_die.rs131.nq,
	u_die.dl36.outp,
	u_die.dw134.outp,
	u_die.dl37.outp,
	u_die.dl38.outp,
	u_die.rs144.q,
	u_die.rs144.nq,
	u_die.dl39.outp,
	u_die.rs205.q,
	u_die.rs205.nq,
	u_die.dl40.outp,
	u_die.rs210.q,
	u_die.rs210.nq,
	u_die.dl41.outp,
	u_die.dw292.outp,
	u_die.dw293.outp,
	u_die.dw298.outp,
	u_die.dw301.outp,
	u_die.dl42.outp,
	u_die.dw305.outp,
	u_die.dw307.outp,
	u_die.dl44.outp,
	u_die.dw319.outp,
	u_die.dl45.outp,
	u_die.rs321.q,
	u_die.rs321.nq,
	u_die.rs322.q,
	u_die.rs322.nq,
	u_die.dl46.outp,
	u_die.dl46_i.outp,
	u_die.rs327.q,
	u_die.rs327.nq,
	u_die.dl47.outp,
	u_die.dl47_i.outp,
	u_die.rs330.q,
	u_die.rs330.nq,
	u_die.dl48.outp,
	u_die.dl48_i.outp,
	u_die.rs332.q,
	u_die.rs332.nq,
	u_die.dw341.outp,
	u_die.dw345.outp,
	u_die.dw346.outp,
	u_die.dw347.outp,
	u_die.dl81.outp,
	u_die.dw359.outp,
	u_die.dl49.outp,
	u_die.dl49_i.outp,
	u_die.rs361.q,
	u_die.rs361.nq,
	u_die.dw369.outp,
	u_die.dw370.outp,
	u_die.dw372.outp,
	u_die.dw373.outp,
	u_die.dw377.outp,
	u_die.dw378_1.outp,
	u_die.dw378_2.outp,
	u_die.dw379_1.outp,
	u_die.dw379_2.outp,
	u_die.dl50.outp,
	u_die.dl51.outp,
	u_die.rs380.q,
	u_die.rs380.nq,
	u_die.dw381.outp,
	u_die.dl52.outp,
	u_die.dw390.outp,
	u_die.dw391.outp,
	u_die.dl53.outp,
	u_die.dw400.outp,
	u_die.dl54.outp,
	u_die.dl55.outp,
	u_die.dw404.outp,
	u_die.dw416.outp,
	u_die.dw417.outp,
	u_die.dw418.outp,
	u_die.dw419.outp,
	u_die.dl73.outp,
	u_die.dl56.outp,
	u_die.dl61.outp,
	u_die.dw430.outp,
	u_die.dw431.outp,
	u_die.dl57.outp,
	u_die.dl58.outp,
	u_die.dl59.outp,
	u_die.dl60.outp,
	u_die.dl62.outp,
	u_die.rs442.q,
	u_die.rs442.nq,
	u_die.dl83.outp,
	u_die.dl84.outp,
	u_die.dw449.outp,
	u_die.dw452.outp,
	u_die.dw453.outp,
	u_die.dl63.outp,
	u_die.dl64.outp,
	u_die.dl65.outp,
	u_die.dl66.outp,
	u_die.dl67.outp,
	u_die.dl68.outp,
	u_die.dl70.outp,
	u_die.dl71.outp,
	u_die.dl72.outp,
	u_die.dw470.outp,
	u_die.dl75.outp,
	u_die.dl76.outp,
	u_die.dl77.outp,
	u_die.dl79.outp,
	u_die.haltrs.q,
	u_die.haltrs.nq,
	u_die.m1rs.q,
	u_die.m1rs.nq};
wire [STO_BITS-1:0] sto_b = {
	u_rtl.w9,
	u_rtl.w30,
	u_rtl.w40,
	u_rtl.w40_i,
	u_rtl.w73,
	u_rtl.w74,
	u_rtl.w78_i,
	u_rtl.w80,
	u_rtl.w92,
	u_rtl.w95_i,
	u_rtl.w100,
	u_rtl.w145,
	u_rtl.w146,
	u_rtl.w147_prev,
	u_rtl.w302,
	u_rtl.w304_r,
	u_rtl.w320,
	u_rtl.w327,
	u_rtl.w329_r,
	u_rtl.w331_r,
	u_rtl.w392,
	u_rtl.w420,
	u_rtl.w425,
	u_rtl.w441,
	u_rtl.w445,
	u_rtl.w450,
	u_rtl.w464,
	u_rtl.w473,
	u_rtl.w476,
	u_rtl.w484,
	u_rtl.w496,
	u_rtl.w498,
	u_rtl.w499,
	u_rtl.w503,
	u_rtl.w510,
	u_rtl.w511,
	u_rtl.w513,
	u_rtl.regs[0][0],
	u_rtl.regs[0][1],
	u_rtl.regs[1][0],
	u_rtl.regs[1][1],
	u_rtl.regs[2][0],
	u_rtl.regs[2][1],
	u_rtl.regs[3][0],
	u_rtl.regs[3][1],
	u_rtl.regs[4][0],
	u_rtl.regs[4][1],
	u_rtl.regs[5][0],
	u_rtl.regs[5][1],
	u_rtl.regs[6][0],
	u_rtl.regs[6][1],
	u_rtl.regs[7][0],
	u_rtl.regs[7][1],
	u_rtl.regs[8][0],
	u_rtl.regs[8][1],
	u_rtl.regs[9][0],
	u_rtl.regs[9][1],
	u_rtl.regs[10][0],
	u_rtl.regs[10][1],
	u_rtl.regs[11][0],
	u_rtl.regs[11][1],
	u_rtl.regs2[0][0],
	u_rtl.regs2[0][1],
	u_rtl.regs2[1][0],
	u_rtl.regs2[1][1],
	u_rtl.w514,
	u_rtl.w515,
	u_rtl.w520,
	u_rtl.w521,
	u_rtl.w522,
	u_rtl.w524,
	u_rtl.w526,
	u_rtl.w527,
	u_rtl.rs1_q,
	u_rtl.rs1_nq,
	u_rtl.dl1_outp,
	u_rtl.rs2_q,
	u_rtl.rs2_nq,
	u_rtl.rs4_q,
	u_rtl.rs4_nq,
	u_rtl.rs5_q,
	u_rtl.rs5_nq,
	u_rtl.dl2_outp,
	u_rtl.rs7_q,
	u_rtl.rs7_nq,
	u_rtl.rs6_q,
	u_rtl.rs6_nq,
	u_rtl.rs8_q,
	u_rtl.rs8_nq,
	u_rtl.rs9_q,
	u_rtl.rs9_nq,
	u_rtl.dl3_outp,
	u_rtl.dl4_outp,
	u_rtl.rs18_q,
	u_rtl.rs18_nq,
	u_rtl.rs19_q,
	u_rtl.rs19_nq,
	u_rtl.rs21_q,
	u_rtl.rs21_nq,
	u_rtl.rs22_q,
	u_rtl.rs22_nq,
	u_rtl.dl5_outp,
	u_rtl.dl6_outp,
	u_rtl.dl7_outp,
	u_rtl.dl8_outp,
	u_rtl.rs31_q,
	u_rtl.rs31_nq,
	u_rtl.dl9_outp,
	u_rtl.rs33_q,
	u_rtl.rs33_nq,
	u_rtl.dl10_outp,
	u_rtl.dl11_outp,
	u_rtl.rs34_q,
	u_rtl.rs34_nq,
	u_rtl.dl12_outp,
	u_rtl.dl82_outp,
	u_rtl.rs37_q,
	u_rtl.rs37_nq,
	u_rtl.dl_w38_outp,
	u_rtl.rs39_q,
	u_rtl.rs39_nq,
	u_rtl.dl13_outp,
	u_rtl.rs44_q,
	u_rtl.rs44_nq,
	u_rtl.dl14_outp,
	u_rtl.dl15_outp,
	u_rtl.dl16_outp,
	u_rtl.dl17_outp,
	u_rtl.dl18_outp,
	u_rtl.rs48_q,
	u_rtl.rs48_nq,
	u_rtl.rs50_q,
	u_rtl.rs50_nq,
	u_rtl.rs51_q,
	u_rtl.rs51_nq,
	u_rtl.dl19_outp,
	u_rtl.dl20_outp,
	u_rtl.rs54_q,
	u_rtl.rs54_nq,
	u_rtl.rs56_q,
	u_rtl.rs56_nq,
	u_rtl.rs58_q,
	u_rtl.rs58_nq,
	u_rtl.rs59_q,
	u_rtl.rs59_nq,
	u_rtl.dl21_outp,
	u_rtl.rs61_q,
	u_rtl.rs61_nq,
	u_rtl.dl22_outp,
	u_rtl.dl23_outp,
	u_rtl.rs63_q,
	u_rtl.rs63_nq,
	u_rtl.dl24_outp,
	u_rtl.rs66_q,
	u_rtl.rs66_nq,
	u_rtl.dl25_outp,
	u_rtl.rs68_q,
	u_rtl.rs68_nq,
	u_rtl.dl26_outp,
	u_rtl.dl27_outp,
	u_rtl.dl28_outp,
	u_rtl.dl43_outp,
	u_rtl.dw98_outp,
	u_rtl.dw99_outp,
	u_rtl.dl29_outp,
	u_rtl.dw104_outp,
	u_rtl.dw107_outp,
	u_rtl.dl30_outp,
	u_rtl.rs109_q,
	u_rtl.rs109_nq,
	u_rtl.rs111_q,
	u_rtl.rs111_nq,
	u_rtl.dw112_outp,
	u_rtl.dl31_outp,
	u_rtl.rs114_q,
	u_rtl.rs114_nq,
	u_rtl.rs115_q,
	u_rtl.rs115_nq,
	u_rtl.dl32_outp,
	u_rtl.rs120_q,
	u_rtl.rs120_nq,
	u_rtl.rs121_q,
	u_rtl.rs121_nq,
	u_rtl.dl33_outp,
	u_rtl.rs123_q,
	u_rtl.rs123_nq,
	u_rtl.dl34_outp,
	u_rtl.rs127_q,
	u_rtl.rs127_nq,
	u_rtl.dl35_outp,
	u_rtl.rsrfsh_q,
	u_rtl.rsrfsh_nq,
	u_rtl.dw130_outp,
	u_rtl.rs131_q,
	u_rtl.rs131_nq,
	u_rtl.dl36_outp,
	u_rtl.dw134_outp,
	u_rtl.dl37_outp,
	u_rtl.dl38_outp,
	u_rtl.rs144_q,
	u_rtl.rs144_nq,
	u_rtl.dl39_outp,
	u_rtl.rs205_q,
	u_rtl.rs205_nq,
	u_rtl.dl40_outp,
	u_rtl.rs210_q,
	u_rtl.rs210_nq,
	u_rtl.dl41_outp,
	u_rtl.dw292_outp,
	u_rtl.dw293_outp,
	u_rtl.dw298_outp,
	u_rtl.dw301_outp,
	u_rtl.dl42_outp,
	u_rtl.dw305_outp,
	u_rtl.dw307_outp,
	u_rtl.dl44_outp,
	u_rtl.dw319_outp,
	u_rtl.dl45_outp,
	u_rtl.rs321_q,
	u_rtl.rs321_nq,
	u_rtl.rs322_q,
	u_rtl.rs322_nq,
	u_rtl.dl46_outp,
	u_rtl.dl46_i_outp,
	u_rtl.rs327_q,
	u_rtl.rs327_nq,
	u_rtl.dl47_outp,
	u_rtl.dl47_i_outp,
	u_rtl.rs330_q,
	u_rtl.rs330_nq,
	u_rtl.dl48_outp,
	u_rtl.dl48_i_outp,
	u_rtl.rs332_q,
	u_rtl.rs332_nq,
	u_rtl.dw341_outp,
	u_rtl.dw345_outp,
	u_rtl.dw346_outp,
	u_rtl.dw347_outp,
	u_rtl.dl81_outp,
	u_rtl.dw359_outp,
	u_rtl.dl49_outp,
	u_rtl.dl49_i_outp,
	u_rtl.rs361_q,
	u_rtl.rs361_nq,
	u_rtl.dw369_outp,
	u_rtl.dw370_outp,
	u_rtl.dw372_outp,
	u_rtl.dw373_outp,
	u_rtl.dw377_outp,
	u_rtl.dw378_1_outp,
	u_rtl.dw378_2_outp,
	u_rtl.dw379_1_outp,
	u_rtl.dw379_2_outp,
	u_rtl.dl50_outp,
	u_rtl.dl51_outp,
	u_rtl.rs380_q,
	u_rtl.rs380_nq,
	u_rtl.dw381_outp,
	u_rtl.dl52_outp,
	u_rtl.dw390_outp,
	u_rtl.dw391_outp,
	u_rtl.dl53_outp,
	u_rtl.dw400_outp,
	u_rtl.dl54_outp,
	u_rtl.dl55_outp,
	u_rtl.dw404_outp,
	u_rtl.dw416_outp,
	u_rtl.dw417_outp,
	u_rtl.dw418_outp,
	u_rtl.dw419_outp,
	u_rtl.dl73_outp,
	u_rtl.dl56_outp,
	u_rtl.dl61_outp,
	u_rtl.dw430_outp,
	u_rtl.dw431_outp,
	u_rtl.dl57_outp,
	u_rtl.dl58_outp,
	u_rtl.dl59_outp,
	u_rtl.dl60_outp,
	u_rtl.dl62_outp,
	u_rtl.rs442_q,
	u_rtl.rs442_nq,
	u_rtl.dl83_outp,
	u_rtl.dl84_outp,
	u_rtl.dw449_outp,
	u_rtl.dw452_outp,
	u_rtl.dw453_outp,
	u_rtl.dl63_outp,
	u_rtl.dl64_outp,
	u_rtl.dl65_outp,
	u_rtl.dl66_outp,
	u_rtl.dl67_outp,
	u_rtl.dl68_outp,
	u_rtl.dl70_outp,
	u_rtl.dl71_outp,
	u_rtl.dl72_outp,
	u_rtl.dw470_outp,
	u_rtl.dl75_outp,
	u_rtl.dl76_outp,
	u_rtl.dl77_outp,
	u_rtl.dl79_outp,
	u_rtl.haltrs_q,
	u_rtl.haltrs_nq,
	u_rtl.m1rs_q,
	u_rtl.m1rs_nq};
task automatic report_storage(input string phase);
	`CMP("w9", u_die.w9, u_rtl.w9)
	`CMP("w30", u_die.w30, u_rtl.w30)
	`CMP("w40", u_die.w40, u_rtl.w40)
	`CMP("w40_i", u_die.w40_i, u_rtl.w40_i)
	`CMP("w73", u_die.w73, u_rtl.w73)
	`CMP("w74", u_die.w74, u_rtl.w74)
	`CMP("w78_i", u_die.w78_i, u_rtl.w78_i)
	`CMP("w80", u_die.w80, u_rtl.w80)
	`CMP("w92", u_die.w92, u_rtl.w92)
	`CMP("w95_i", u_die.w95_i, u_rtl.w95_i)
	`CMP("w100", u_die.w100, u_rtl.w100)
	`CMP("w145", u_die.w145, u_rtl.w145)
	`CMP("w146", u_die.w146, u_rtl.w146)
	`CMP("w147_prev", u_die.w147_prev, u_rtl.w147_prev)
	`CMP("w302", u_die.w302, u_rtl.w302)
	`CMP("w304_r", u_die.w304_r, u_rtl.w304_r)
	`CMP("w320", u_die.w320, u_rtl.w320)
	`CMP("w327", u_die.w327, u_rtl.w327)
	`CMP("w329_r", u_die.w329_r, u_rtl.w329_r)
	`CMP("w331_r", u_die.w331_r, u_rtl.w331_r)
	`CMP("w392", u_die.w392, u_rtl.w392)
	`CMP("w420", u_die.w420, u_rtl.w420)
	`CMP("w425", u_die.w425, u_rtl.w425)
	`CMP("w441", u_die.w441, u_rtl.w441)
	`CMP("w445", u_die.w445, u_rtl.w445)
	`CMP("w450", u_die.w450, u_rtl.w450)
	`CMP("w464", u_die.w464, u_rtl.w464)
	`CMP("w473", u_die.w473, u_rtl.w473)
	`CMP("w476", u_die.w476, u_rtl.w476)
	`CMP("w484", u_die.w484, u_rtl.w484)
	`CMP("w496", u_die.w496, u_rtl.w496)
	`CMP("w498", u_die.w498, u_rtl.w498)
	`CMP("w499", u_die.w499, u_rtl.w499)
	`CMP("w503", u_die.w503, u_rtl.w503)
	`CMP("w510", u_die.w510, u_rtl.w510)
	`CMP("w511", u_die.w511, u_rtl.w511)
	`CMP("w513", u_die.w513, u_rtl.w513)
	`CMP("regs[0][0]", u_die.regs[0][0], u_rtl.regs[0][0])
	`CMP("regs[0][1]", u_die.regs[0][1], u_rtl.regs[0][1])
	`CMP("regs[1][0]", u_die.regs[1][0], u_rtl.regs[1][0])
	`CMP("regs[1][1]", u_die.regs[1][1], u_rtl.regs[1][1])
	`CMP("regs[2][0]", u_die.regs[2][0], u_rtl.regs[2][0])
	`CMP("regs[2][1]", u_die.regs[2][1], u_rtl.regs[2][1])
	`CMP("regs[3][0]", u_die.regs[3][0], u_rtl.regs[3][0])
	`CMP("regs[3][1]", u_die.regs[3][1], u_rtl.regs[3][1])
	`CMP("regs[4][0]", u_die.regs[4][0], u_rtl.regs[4][0])
	`CMP("regs[4][1]", u_die.regs[4][1], u_rtl.regs[4][1])
	`CMP("regs[5][0]", u_die.regs[5][0], u_rtl.regs[5][0])
	`CMP("regs[5][1]", u_die.regs[5][1], u_rtl.regs[5][1])
	`CMP("regs[6][0]", u_die.regs[6][0], u_rtl.regs[6][0])
	`CMP("regs[6][1]", u_die.regs[6][1], u_rtl.regs[6][1])
	`CMP("regs[7][0]", u_die.regs[7][0], u_rtl.regs[7][0])
	`CMP("regs[7][1]", u_die.regs[7][1], u_rtl.regs[7][1])
	`CMP("regs[8][0]", u_die.regs[8][0], u_rtl.regs[8][0])
	`CMP("regs[8][1]", u_die.regs[8][1], u_rtl.regs[8][1])
	`CMP("regs[9][0]", u_die.regs[9][0], u_rtl.regs[9][0])
	`CMP("regs[9][1]", u_die.regs[9][1], u_rtl.regs[9][1])
	`CMP("regs[10][0]", u_die.regs[10][0], u_rtl.regs[10][0])
	`CMP("regs[10][1]", u_die.regs[10][1], u_rtl.regs[10][1])
	`CMP("regs[11][0]", u_die.regs[11][0], u_rtl.regs[11][0])
	`CMP("regs[11][1]", u_die.regs[11][1], u_rtl.regs[11][1])
	`CMP("regs2[0][0]", u_die.regs2[0][0], u_rtl.regs2[0][0])
	`CMP("regs2[0][1]", u_die.regs2[0][1], u_rtl.regs2[0][1])
	`CMP("regs2[1][0]", u_die.regs2[1][0], u_rtl.regs2[1][0])
	`CMP("regs2[1][1]", u_die.regs2[1][1], u_rtl.regs2[1][1])
	`CMP("w514", u_die.w514, u_rtl.w514)
	`CMP("w515", u_die.w515, u_rtl.w515)
	`CMP("w520", u_die.w520, u_rtl.w520)
	`CMP("w521", u_die.w521, u_rtl.w521)
	`CMP("w522", u_die.w522, u_rtl.w522)
	`CMP("w524", u_die.w524, u_rtl.w524)
	`CMP("w526", u_die.w526, u_rtl.w526)
	`CMP("w527", u_die.w527, u_rtl.w527)
	`CMP("rs1.q", u_die.rs1.q, u_rtl.rs1_q)
	`CMP("rs1.nq", u_die.rs1.nq, u_rtl.rs1_nq)
	`CMP("dl1.outp", u_die.dl1.outp, u_rtl.dl1_outp)
	`CMP("rs2.q", u_die.rs2.q, u_rtl.rs2_q)
	`CMP("rs2.nq", u_die.rs2.nq, u_rtl.rs2_nq)
	`CMP("rs4.q", u_die.rs4.q, u_rtl.rs4_q)
	`CMP("rs4.nq", u_die.rs4.nq, u_rtl.rs4_nq)
	`CMP("rs5.q", u_die.rs5.q, u_rtl.rs5_q)
	`CMP("rs5.nq", u_die.rs5.nq, u_rtl.rs5_nq)
	`CMP("dl2.outp", u_die.dl2.outp, u_rtl.dl2_outp)
	`CMP("rs7.q", u_die.rs7.q, u_rtl.rs7_q)
	`CMP("rs7.nq", u_die.rs7.nq, u_rtl.rs7_nq)
	`CMP("rs6.q", u_die.rs6.q, u_rtl.rs6_q)
	`CMP("rs6.nq", u_die.rs6.nq, u_rtl.rs6_nq)
	`CMP("rs8.q", u_die.rs8.q, u_rtl.rs8_q)
	`CMP("rs8.nq", u_die.rs8.nq, u_rtl.rs8_nq)
	`CMP("rs9.q", u_die.rs9.q, u_rtl.rs9_q)
	`CMP("rs9.nq", u_die.rs9.nq, u_rtl.rs9_nq)
	`CMP("dl3.outp", u_die.dl3.outp, u_rtl.dl3_outp)
	`CMP("dl4.outp", u_die.dl4.outp, u_rtl.dl4_outp)
	`CMP("rs18.q", u_die.rs18.q, u_rtl.rs18_q)
	`CMP("rs18.nq", u_die.rs18.nq, u_rtl.rs18_nq)
	`CMP("rs19.q", u_die.rs19.q, u_rtl.rs19_q)
	`CMP("rs19.nq", u_die.rs19.nq, u_rtl.rs19_nq)
	`CMP("rs21.q", u_die.rs21.q, u_rtl.rs21_q)
	`CMP("rs21.nq", u_die.rs21.nq, u_rtl.rs21_nq)
	`CMP("rs22.q", u_die.rs22.q, u_rtl.rs22_q)
	`CMP("rs22.nq", u_die.rs22.nq, u_rtl.rs22_nq)
	`CMP("dl5.outp", u_die.dl5.outp, u_rtl.dl5_outp)
	`CMP("dl6.outp", u_die.dl6.outp, u_rtl.dl6_outp)
	`CMP("dl7.outp", u_die.dl7.outp, u_rtl.dl7_outp)
	`CMP("dl8.outp", u_die.dl8.outp, u_rtl.dl8_outp)
	`CMP("rs31.q", u_die.rs31.q, u_rtl.rs31_q)
	`CMP("rs31.nq", u_die.rs31.nq, u_rtl.rs31_nq)
	`CMP("dl9.outp", u_die.dl9.outp, u_rtl.dl9_outp)
	`CMP("rs33.q", u_die.rs33.q, u_rtl.rs33_q)
	`CMP("rs33.nq", u_die.rs33.nq, u_rtl.rs33_nq)
	`CMP("dl10.outp", u_die.dl10.outp, u_rtl.dl10_outp)
	`CMP("dl11.outp", u_die.dl11.outp, u_rtl.dl11_outp)
	`CMP("rs34.q", u_die.rs34.q, u_rtl.rs34_q)
	`CMP("rs34.nq", u_die.rs34.nq, u_rtl.rs34_nq)
	`CMP("dl12.outp", u_die.dl12.outp, u_rtl.dl12_outp)
	`CMP("dl82.outp", u_die.dl82.outp, u_rtl.dl82_outp)
	`CMP("rs37.q", u_die.rs37.q, u_rtl.rs37_q)
	`CMP("rs37.nq", u_die.rs37.nq, u_rtl.rs37_nq)
	`CMP("dl_w38.outp", u_die.dl_w38.outp, u_rtl.dl_w38_outp)
	`CMP("rs39.q", u_die.rs39.q, u_rtl.rs39_q)
	`CMP("rs39.nq", u_die.rs39.nq, u_rtl.rs39_nq)
	`CMP("dl13.outp", u_die.dl13.outp, u_rtl.dl13_outp)
	`CMP("rs44.q", u_die.rs44.q, u_rtl.rs44_q)
	`CMP("rs44.nq", u_die.rs44.nq, u_rtl.rs44_nq)
	`CMP("dl14.outp", u_die.dl14.outp, u_rtl.dl14_outp)
	`CMP("dl15.outp", u_die.dl15.outp, u_rtl.dl15_outp)
	`CMP("dl16.outp", u_die.dl16.outp, u_rtl.dl16_outp)
	`CMP("dl17.outp", u_die.dl17.outp, u_rtl.dl17_outp)
	`CMP("dl18.outp", u_die.dl18.outp, u_rtl.dl18_outp)
	`CMP("rs48.q", u_die.rs48.q, u_rtl.rs48_q)
	`CMP("rs48.nq", u_die.rs48.nq, u_rtl.rs48_nq)
	`CMP("rs50.q", u_die.rs50.q, u_rtl.rs50_q)
	`CMP("rs50.nq", u_die.rs50.nq, u_rtl.rs50_nq)
	`CMP("rs51.q", u_die.rs51.q, u_rtl.rs51_q)
	`CMP("rs51.nq", u_die.rs51.nq, u_rtl.rs51_nq)
	`CMP("dl19.outp", u_die.dl19.outp, u_rtl.dl19_outp)
	`CMP("dl20.outp", u_die.dl20.outp, u_rtl.dl20_outp)
	`CMP("rs54.q", u_die.rs54.q, u_rtl.rs54_q)
	`CMP("rs54.nq", u_die.rs54.nq, u_rtl.rs54_nq)
	`CMP("rs56.q", u_die.rs56.q, u_rtl.rs56_q)
	`CMP("rs56.nq", u_die.rs56.nq, u_rtl.rs56_nq)
	`CMP("rs58.q", u_die.rs58.q, u_rtl.rs58_q)
	`CMP("rs58.nq", u_die.rs58.nq, u_rtl.rs58_nq)
	`CMP("rs59.q", u_die.rs59.q, u_rtl.rs59_q)
	`CMP("rs59.nq", u_die.rs59.nq, u_rtl.rs59_nq)
	`CMP("dl21.outp", u_die.dl21.outp, u_rtl.dl21_outp)
	`CMP("rs61.q", u_die.rs61.q, u_rtl.rs61_q)
	`CMP("rs61.nq", u_die.rs61.nq, u_rtl.rs61_nq)
	`CMP("dl22.outp", u_die.dl22.outp, u_rtl.dl22_outp)
	`CMP("dl23.outp", u_die.dl23.outp, u_rtl.dl23_outp)
	`CMP("rs63.q", u_die.rs63.q, u_rtl.rs63_q)
	`CMP("rs63.nq", u_die.rs63.nq, u_rtl.rs63_nq)
	`CMP("dl24.outp", u_die.dl24.outp, u_rtl.dl24_outp)
	`CMP("rs66.q", u_die.rs66.q, u_rtl.rs66_q)
	`CMP("rs66.nq", u_die.rs66.nq, u_rtl.rs66_nq)
	`CMP("dl25.outp", u_die.dl25.outp, u_rtl.dl25_outp)
	`CMP("rs68.q", u_die.rs68.q, u_rtl.rs68_q)
	`CMP("rs68.nq", u_die.rs68.nq, u_rtl.rs68_nq)
	`CMP("dl26.outp", u_die.dl26.outp, u_rtl.dl26_outp)
	`CMP("dl27.outp", u_die.dl27.outp, u_rtl.dl27_outp)
	`CMP("dl28.outp", u_die.dl28.outp, u_rtl.dl28_outp)
	`CMP("dl43.outp", u_die.dl43.outp, u_rtl.dl43_outp)
	`CMP("dw98.outp", u_die.dw98.outp, u_rtl.dw98_outp)
	`CMP("dw99.outp", u_die.dw99.outp, u_rtl.dw99_outp)
	`CMP("dl29.outp", u_die.dl29.outp, u_rtl.dl29_outp)
	`CMP("dw104.outp", u_die.dw104.outp, u_rtl.dw104_outp)
	`CMP("dw107.outp", u_die.dw107.outp, u_rtl.dw107_outp)
	`CMP("dl30.outp", u_die.dl30.outp, u_rtl.dl30_outp)
	`CMP("rs109.q", u_die.rs109.q, u_rtl.rs109_q)
	`CMP("rs109.nq", u_die.rs109.nq, u_rtl.rs109_nq)
	`CMP("rs111.q", u_die.rs111.q, u_rtl.rs111_q)
	`CMP("rs111.nq", u_die.rs111.nq, u_rtl.rs111_nq)
	`CMP("dw112.outp", u_die.dw112.outp, u_rtl.dw112_outp)
	`CMP("dl31.outp", u_die.dl31.outp, u_rtl.dl31_outp)
	`CMP("rs114.q", u_die.rs114.q, u_rtl.rs114_q)
	`CMP("rs114.nq", u_die.rs114.nq, u_rtl.rs114_nq)
	`CMP("rs115.q", u_die.rs115.q, u_rtl.rs115_q)
	`CMP("rs115.nq", u_die.rs115.nq, u_rtl.rs115_nq)
	`CMP("dl32.outp", u_die.dl32.outp, u_rtl.dl32_outp)
	`CMP("rs120.q", u_die.rs120.q, u_rtl.rs120_q)
	`CMP("rs120.nq", u_die.rs120.nq, u_rtl.rs120_nq)
	`CMP("rs121.q", u_die.rs121.q, u_rtl.rs121_q)
	`CMP("rs121.nq", u_die.rs121.nq, u_rtl.rs121_nq)
	`CMP("dl33.outp", u_die.dl33.outp, u_rtl.dl33_outp)
	`CMP("rs123.q", u_die.rs123.q, u_rtl.rs123_q)
	`CMP("rs123.nq", u_die.rs123.nq, u_rtl.rs123_nq)
	`CMP("dl34.outp", u_die.dl34.outp, u_rtl.dl34_outp)
	`CMP("rs127.q", u_die.rs127.q, u_rtl.rs127_q)
	`CMP("rs127.nq", u_die.rs127.nq, u_rtl.rs127_nq)
	`CMP("dl35.outp", u_die.dl35.outp, u_rtl.dl35_outp)
	`CMP("rsrfsh.q", u_die.rsrfsh.q, u_rtl.rsrfsh_q)
	`CMP("rsrfsh.nq", u_die.rsrfsh.nq, u_rtl.rsrfsh_nq)
	`CMP("dw130.outp", u_die.dw130.outp, u_rtl.dw130_outp)
	`CMP("rs131.q", u_die.rs131.q, u_rtl.rs131_q)
	`CMP("rs131.nq", u_die.rs131.nq, u_rtl.rs131_nq)
	`CMP("dl36.outp", u_die.dl36.outp, u_rtl.dl36_outp)
	`CMP("dw134.outp", u_die.dw134.outp, u_rtl.dw134_outp)
	`CMP("dl37.outp", u_die.dl37.outp, u_rtl.dl37_outp)
	`CMP("dl38.outp", u_die.dl38.outp, u_rtl.dl38_outp)
	`CMP("rs144.q", u_die.rs144.q, u_rtl.rs144_q)
	`CMP("rs144.nq", u_die.rs144.nq, u_rtl.rs144_nq)
	`CMP("dl39.outp", u_die.dl39.outp, u_rtl.dl39_outp)
	`CMP("rs205.q", u_die.rs205.q, u_rtl.rs205_q)
	`CMP("rs205.nq", u_die.rs205.nq, u_rtl.rs205_nq)
	`CMP("dl40.outp", u_die.dl40.outp, u_rtl.dl40_outp)
	`CMP("rs210.q", u_die.rs210.q, u_rtl.rs210_q)
	`CMP("rs210.nq", u_die.rs210.nq, u_rtl.rs210_nq)
	`CMP("dl41.outp", u_die.dl41.outp, u_rtl.dl41_outp)
	`CMP("dw292.outp", u_die.dw292.outp, u_rtl.dw292_outp)
	`CMP("dw293.outp", u_die.dw293.outp, u_rtl.dw293_outp)
	`CMP("dw298.outp", u_die.dw298.outp, u_rtl.dw298_outp)
	`CMP("dw301.outp", u_die.dw301.outp, u_rtl.dw301_outp)
	`CMP("dl42.outp", u_die.dl42.outp, u_rtl.dl42_outp)
	`CMP("dw305.outp", u_die.dw305.outp, u_rtl.dw305_outp)
	`CMP("dw307.outp", u_die.dw307.outp, u_rtl.dw307_outp)
	`CMP("dl44.outp", u_die.dl44.outp, u_rtl.dl44_outp)
	`CMP("dw319.outp", u_die.dw319.outp, u_rtl.dw319_outp)
	`CMP("dl45.outp", u_die.dl45.outp, u_rtl.dl45_outp)
	`CMP("rs321.q", u_die.rs321.q, u_rtl.rs321_q)
	`CMP("rs321.nq", u_die.rs321.nq, u_rtl.rs321_nq)
	`CMP("rs322.q", u_die.rs322.q, u_rtl.rs322_q)
	`CMP("rs322.nq", u_die.rs322.nq, u_rtl.rs322_nq)
	`CMP("dl46.outp", u_die.dl46.outp, u_rtl.dl46_outp)
	`CMP("dl46_i.outp", u_die.dl46_i.outp, u_rtl.dl46_i_outp)
	`CMP("rs327.q", u_die.rs327.q, u_rtl.rs327_q)
	`CMP("rs327.nq", u_die.rs327.nq, u_rtl.rs327_nq)
	`CMP("dl47.outp", u_die.dl47.outp, u_rtl.dl47_outp)
	`CMP("dl47_i.outp", u_die.dl47_i.outp, u_rtl.dl47_i_outp)
	`CMP("rs330.q", u_die.rs330.q, u_rtl.rs330_q)
	`CMP("rs330.nq", u_die.rs330.nq, u_rtl.rs330_nq)
	`CMP("dl48.outp", u_die.dl48.outp, u_rtl.dl48_outp)
	`CMP("dl48_i.outp", u_die.dl48_i.outp, u_rtl.dl48_i_outp)
	`CMP("rs332.q", u_die.rs332.q, u_rtl.rs332_q)
	`CMP("rs332.nq", u_die.rs332.nq, u_rtl.rs332_nq)
	`CMP("dw341.outp", u_die.dw341.outp, u_rtl.dw341_outp)
	`CMP("dw345.outp", u_die.dw345.outp, u_rtl.dw345_outp)
	`CMP("dw346.outp", u_die.dw346.outp, u_rtl.dw346_outp)
	`CMP("dw347.outp", u_die.dw347.outp, u_rtl.dw347_outp)
	`CMP("dl81.outp", u_die.dl81.outp, u_rtl.dl81_outp)
	`CMP("dw359.outp", u_die.dw359.outp, u_rtl.dw359_outp)
	`CMP("dl49.outp", u_die.dl49.outp, u_rtl.dl49_outp)
	`CMP("dl49_i.outp", u_die.dl49_i.outp, u_rtl.dl49_i_outp)
	`CMP("rs361.q", u_die.rs361.q, u_rtl.rs361_q)
	`CMP("rs361.nq", u_die.rs361.nq, u_rtl.rs361_nq)
	`CMP("dw369.outp", u_die.dw369.outp, u_rtl.dw369_outp)
	`CMP("dw370.outp", u_die.dw370.outp, u_rtl.dw370_outp)
	`CMP("dw372.outp", u_die.dw372.outp, u_rtl.dw372_outp)
	`CMP("dw373.outp", u_die.dw373.outp, u_rtl.dw373_outp)
	`CMP("dw377.outp", u_die.dw377.outp, u_rtl.dw377_outp)
	`CMP("dw378_1.outp", u_die.dw378_1.outp, u_rtl.dw378_1_outp)
	`CMP("dw378_2.outp", u_die.dw378_2.outp, u_rtl.dw378_2_outp)
	`CMP("dw379_1.outp", u_die.dw379_1.outp, u_rtl.dw379_1_outp)
	`CMP("dw379_2.outp", u_die.dw379_2.outp, u_rtl.dw379_2_outp)
	`CMP("dl50.outp", u_die.dl50.outp, u_rtl.dl50_outp)
	`CMP("dl51.outp", u_die.dl51.outp, u_rtl.dl51_outp)
	`CMP("rs380.q", u_die.rs380.q, u_rtl.rs380_q)
	`CMP("rs380.nq", u_die.rs380.nq, u_rtl.rs380_nq)
	`CMP("dw381.outp", u_die.dw381.outp, u_rtl.dw381_outp)
	`CMP("dl52.outp", u_die.dl52.outp, u_rtl.dl52_outp)
	`CMP("dw390.outp", u_die.dw390.outp, u_rtl.dw390_outp)
	`CMP("dw391.outp", u_die.dw391.outp, u_rtl.dw391_outp)
	`CMP("dl53.outp", u_die.dl53.outp, u_rtl.dl53_outp)
	`CMP("dw400.outp", u_die.dw400.outp, u_rtl.dw400_outp)
	`CMP("dl54.outp", u_die.dl54.outp, u_rtl.dl54_outp)
	`CMP("dl55.outp", u_die.dl55.outp, u_rtl.dl55_outp)
	`CMP("dw404.outp", u_die.dw404.outp, u_rtl.dw404_outp)
	`CMP("dw416.outp", u_die.dw416.outp, u_rtl.dw416_outp)
	`CMP("dw417.outp", u_die.dw417.outp, u_rtl.dw417_outp)
	`CMP("dw418.outp", u_die.dw418.outp, u_rtl.dw418_outp)
	`CMP("dw419.outp", u_die.dw419.outp, u_rtl.dw419_outp)
	`CMP("dl73.outp", u_die.dl73.outp, u_rtl.dl73_outp)
	`CMP("dl56.outp", u_die.dl56.outp, u_rtl.dl56_outp)
	`CMP("dl61.outp", u_die.dl61.outp, u_rtl.dl61_outp)
	`CMP("dw430.outp", u_die.dw430.outp, u_rtl.dw430_outp)
	`CMP("dw431.outp", u_die.dw431.outp, u_rtl.dw431_outp)
	`CMP("dl57.outp", u_die.dl57.outp, u_rtl.dl57_outp)
	`CMP("dl58.outp", u_die.dl58.outp, u_rtl.dl58_outp)
	`CMP("dl59.outp", u_die.dl59.outp, u_rtl.dl59_outp)
	`CMP("dl60.outp", u_die.dl60.outp, u_rtl.dl60_outp)
	`CMP("dl62.outp", u_die.dl62.outp, u_rtl.dl62_outp)
	`CMP("rs442.q", u_die.rs442.q, u_rtl.rs442_q)
	`CMP("rs442.nq", u_die.rs442.nq, u_rtl.rs442_nq)
	`CMP("dl83.outp", u_die.dl83.outp, u_rtl.dl83_outp)
	`CMP("dl84.outp", u_die.dl84.outp, u_rtl.dl84_outp)
	`CMP("dw449.outp", u_die.dw449.outp, u_rtl.dw449_outp)
	`CMP("dw452.outp", u_die.dw452.outp, u_rtl.dw452_outp)
	`CMP("dw453.outp", u_die.dw453.outp, u_rtl.dw453_outp)
	`CMP("dl63.outp", u_die.dl63.outp, u_rtl.dl63_outp)
	`CMP("dl64.outp", u_die.dl64.outp, u_rtl.dl64_outp)
	`CMP("dl65.outp", u_die.dl65.outp, u_rtl.dl65_outp)
	`CMP("dl66.outp", u_die.dl66.outp, u_rtl.dl66_outp)
	`CMP("dl67.outp", u_die.dl67.outp, u_rtl.dl67_outp)
	`CMP("dl68.outp", u_die.dl68.outp, u_rtl.dl68_outp)
	`CMP("dl70.outp", u_die.dl70.outp, u_rtl.dl70_outp)
	`CMP("dl71.outp", u_die.dl71.outp, u_rtl.dl71_outp)
	`CMP("dl72.outp", u_die.dl72.outp, u_rtl.dl72_outp)
	`CMP("dw470.outp", u_die.dw470.outp, u_rtl.dw470_outp)
	`CMP("dl75.outp", u_die.dl75.outp, u_rtl.dl75_outp)
	`CMP("dl76.outp", u_die.dl76.outp, u_rtl.dl76_outp)
	`CMP("dl77.outp", u_die.dl77.outp, u_rtl.dl77_outp)
	`CMP("dl79.outp", u_die.dl79.outp, u_rtl.dl79_outp)
	`CMP("haltrs.q", u_die.haltrs.q, u_rtl.haltrs_q)
	`CMP("haltrs.nq", u_die.haltrs.nq, u_rtl.haltrs_nq)
	`CMP("m1rs.q", u_die.m1rs.q, u_rtl.m1rs_q)
	`CMP("m1rs.nq", u_die.m1rs.nq, u_rtl.m1rs_nq)
endtask
