#!/usr/bin/env bash
# gen_compare.sh [die_sigs] [dut_sigs] [out.svh]
#   Build the storage_compare module (identical-hierarchy XMR comparator over every
#   storage element that exists in BOTH die and dut).  For ym3438_rtl every storage
#   path exists in both; for ym3438_opt the collapsed cells' v1/v2 are absent from
#   the dut, so only the still-1:1 storage (kept prescaler cells, latches, rs
#   triggers, explicit regs) is compared -- exactly "every node that still exists
#   1:1".  Outputs are always compared separately in the testbench.
set -e
export PATH="/c/Program Files/Git/usr/bin:$PATH"
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
DIE="${1:-sigs_die.txt}"
DUT="${2:-sigs_dut.txt}"
OUTF="${3:-storage_compare.svh}"

perl -e '
my ($dief,$dutf,$outf) = @ARGV;
my %dut;
open(my $u, "<", $dutf) or die; while (<$u>){ chomp; s/\r//; if (m{^/tb_ym3438/dut/(.+)$}){ $dut{$1}=1; } } close $u;
my @paths;
open(my $fh, "<", $dief) or die;
while (<$fh>) {
    chomp; s/\r//;
    next unless m{^/tb_ym3438/die/(.+)$};
    my $rel = $1;
    my $leaf = $rel; $leaf =~ s{.*/}{};
    next unless $leaf =~ /^(v1|v2|mem|q|nq|sine_lut_out|pow_lut_out|data_o_r|status_time|ch_out_l|ch_pan_l|dac_out_enable_l|dac_out_enable_2612_l|dac_index_l)$/;
    next unless $dut{$rel};          # keep only storage that still exists 1:1 in dut
    push @paths, $rel;
}
close $fh;
my $n = scalar @paths;
open(my $o, ">", $outf) or die;
print $o "// $outf -- GENERATED by gen_compare.sh.  $n storage cells compared 1:1.\n";
print $o "module storage_compare;\n\twire [$n-1:0] mm;\n";
my $k=0;
for my $p (@paths){ my $sv=$p; $sv=~s{/}{.}g;
  printf $o "\tassign mm[%d] = (tb_ym3438.die.%s !== tb_ym3438.dut.%s);\n",$k,$sv,$sv; $k++; }
print $o "\twire mismatch = |mm;\n\ttask report;\n\tbegin\n";
$k=0;
for my $p (@paths){ my $sv=$p; $sv=~s{/}{.}g;
  printf $o "\t\tif (mm[%d]) \$display(\"  [%d] %s  die=%%h dut=%%h\", tb_ym3438.die.%s, tb_ym3438.dut.%s);\n",$k,$k,$p,$sv,$sv; $k++; }
print $o "\tend\n\tendtask\nendmodule\n";
close $o;
print "wrote $outf : $n storage cells\n";
' "$DIE" "$DUT" "$OUTF"
