#!/usr/bin/env bash
# gen_srout.sh [die_sigs] [out.svh]
#   Build srout_compare -- an identical-hierarchy XMR comparator over the sr_out of
#   EVERY ym_sr_bit instance (die vs dut).  Unlike storage_compare (which compares
#   v1/v2 and so only works for the 1:1 dut), this compares the cell OUTPUT net,
#   which exists in both the die (two-register ym_sr_bit) and the collapsed dut
#   (single-FF ym_sr_bit_opt) -- so it localises the FIRST collapse divergence in
#   ym3438_opt.v to the exact cell.  Wired into tb_ym3438 under +OPT, enabled by
#   +SROUT.  Diagnostic only; it never replaces the primary-output comparison.
#   Regenerate sigs_die.txt via dump_sigs.do if the die hierarchy changes.
set -e
export PATH="/c/Program Files/Git/usr/bin:$PATH"
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"
DIE="${1:-sigs_die.txt}"
OUTF="${2:-srout_compare.svh}"

perl -e '
my ($dief,$outf) = @ARGV;
open(my $fh,"<",$dief) or die;
my (%seen,@u);
while(<$fh>){ chomp; s/\r//; next unless m{^/tb_ym3438/die/(.+)/v1$}; my $c=$1; next if $seen{$c}++; push @u,$c; }
close $fh;
my $n=scalar @u;
open(my $o,">",$outf) or die;
print $o "// srout_compare.svh -- GENERATED by gen_srout.sh.  Compares sr_out of every\n";
print $o "// ym_sr_bit instance (die vs dut) to localise the first collapse divergence.\n";
print $o "// Diagnostic only (enabled by +SROUT); never replaces the output comparison.\n";
print $o "module srout_compare;\n\twire [$n-1:0] mm;\n";
my $k=0;
for my $p (@u){ my $sv=$p; $sv=~s{/}{.}g;
  printf $o "\tassign mm[%d] = (tb_ym3438.die.%s.sr_out !== tb_ym3438.dut.%s.sr_out);\n",$k,$sv,$sv; $k++; }
print $o "\twire mismatch = |mm;\n\ttask report;\n\tbegin\n";
$k=0;
for my $p (@u){ my $sv=$p; $sv=~s{/}{.}g;
  printf $o "\t\tif (mm[%d]) \$display(\"  SROUT-DIVERGE %s  die=%%b dut=%%b\", tb_ym3438.die.%s.sr_out, tb_ym3438.dut.%s.sr_out);\n",$k,$p,$sv,$sv; $k++; }
print $o "\tend\n\tendtask\nendmodule\n";
close $o;
print "wrote $outf : $n cells\n";
' "$DIE" "$OUTF"
