/*
 * ym3438_rtl.v -- STAGE 1: strict 1:1 synthesis-friendly representation of the
 * NukedMD die-level YM3438/YM2612 FM (rtl/nuked-md/ym3438.v + ym3438_*.v +
 * the ym_lib.v cells it uses).  GENERATED by sim/ym3438/gen_rtl.sh -- do not
 * hand-edit; edit the generator.
 *
 * Every module is renamed <name>_rtl and every instantiation retargeted to the
 * _rtl type.  All combinational logic (assign/wire/generate/expressions) is
 * copied verbatim from the die sources.  The ym_lib primitives are emitted here,
 * renamed and self-contained, with byte-identical per-MCLK semantics EXCEPT the
 * three transparent latches, whose recirculating mux `mem <= en?inp:mem` becomes
 * the exactly-equivalent clock enable `if (en) mem <= inp`.  Master-slave pairs
 * (ym_sr_bit v1/v2) are kept as two registers with the identical ym_lib equation.
 * MCLK stays the clock.  The primitive internal hierarchy is preserved verbatim,
 * so ym3438 (die) and ym3438_rtl elaborate to an identical signal tree; the A/B
 * bench in sim/ym3438 relies on that to compare every storage element by identity.
 *
 * This file is space-neutral by design (see docs/CONVERSION_PLAN.md).  The
 * register saving comes in STAGE 2 (ym3438_opt.v), which collapses the ym_sr_bit
 * master-slave pairs on the genuine internal FM phases into single flip-flops.
 */

`default_nettype wire

// ------------------------------------------------------------------------------
//  ym_lib primitive cells used by the FM, renamed <name>_rtl and self-contained.
//  Identical per-MCLK semantics to rtl/nuked-md/ym_lib.v; identical internal
//  hierarchy (same instance/generate/reg names) so the die model and this RTL
//  elaborate to the same signal tree.  Only the transparent-latch recirculating
//  mux is rewritten to a clock enable (exactly equivalent every posedge MCLK).
// ------------------------------------------------------------------------------

module ym_sr_bit_rtl #(parameter SR_LENGTH = 1)
	(
	input MCLK,
	input c1,
	input c2,
	input bit_in,
	output sr_out
	);

	reg [SR_LENGTH-1:0] v1 = 0;
	reg [SR_LENGTH-1:0] v2 = 0;

	wire [SR_LENGTH-1:0] v2_assign = c2 ? v1 : v2;

	assign sr_out = v2[SR_LENGTH-1];

	always @(posedge MCLK)
	begin
		if (c1)
		begin
			if (SR_LENGTH == 1)
				v1 <= bit_in;
			else
				v1 <= { v2[SR_LENGTH-2:0], bit_in };
		end
		v2 <= v2_assign;
	end
endmodule

module ym_sr_bit_array_rtl #(parameter SR_LENGTH = 1, DATA_WIDTH = 1)
	(
	input MCLK,
	input c1,
	input c2,
	input [DATA_WIDTH-1:0] data_in,
	output [DATA_WIDTH-1:0] data_out
	);

	wire out[0:DATA_WIDTH-1];

	generate
		genvar i;
		for (i = 0; i < DATA_WIDTH; i = i + 1)
		begin : l1
			ym_sr_bit_rtl #(.SR_LENGTH(SR_LENGTH)) sr (
			.MCLK(MCLK),
			.c1(c1),
			.c2(c2),
			.bit_in(data_in[i]),
			.sr_out(out[i])
			);

			assign data_out[i] = out[i];
		end
	endgenerate

endmodule

module ym_cnt_bit_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input c1,
	input c2,
	input c_in,
	input reset,
	output [DATA_WIDTH-1:0] val,
	output c_out
	);

	wire [DATA_WIDTH-1:0] data_in;
	wire [DATA_WIDTH-1:0] data_out;
	wire [DATA_WIDTH:0] sum;

	ym_sr_bit_array_rtl #(.DATA_WIDTH(DATA_WIDTH)) mem
		(
		.MCLK(MCLK),
		.c1(c1),
		.c2(c2),
		.data_in(data_in),
		.data_out(data_out)
		);

	assign sum = { 1'h0, data_out } + {{DATA_WIDTH{1'h0}}, c_in};
	assign val = data_out;
	assign data_in = reset ? {DATA_WIDTH{1'h0}} : sum[DATA_WIDTH-1:0];
	assign c_out = sum[DATA_WIDTH];

endmodule

module ym_cnt_bit_load_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input c1,
	input c2,
	input c_in,
	input reset,
	input load,
	input [DATA_WIDTH-1:0] load_val,
	output [DATA_WIDTH-1:0] val,
	output c_out
	);

	wire [DATA_WIDTH-1:0] data_in;
	wire [DATA_WIDTH-1:0] data_out;
	wire [DATA_WIDTH:0] sum;

	ym_sr_bit_array_rtl #(.DATA_WIDTH(DATA_WIDTH)) mem
		(
		.MCLK(MCLK),
		.c1(c1),
		.c2(c2),
		.data_in(data_in),
		.data_out(data_out)
		);

	wire [DATA_WIDTH-1:0] base_val = load ? load_val : data_out;

	assign sum = {1'h0, base_val} + {{DATA_WIDTH{1'h0}},c_in};
	assign data_in = reset ? {DATA_WIDTH{1'h0}} : sum[DATA_WIDTH-1:0];
	assign val = data_out;
	assign c_out = sum[DATA_WIDTH];

endmodule

module ym_dbg_read_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input c1,
	input c2,
	input prev,
	input load,
	input [DATA_WIDTH-1:0] load_val,
	output next
	);

	wire [DATA_WIDTH-1:0] data_in;
	wire [DATA_WIDTH-1:0] data_out;

	ym_sr_bit_array_rtl #(.DATA_WIDTH(DATA_WIDTH)) mem
		(
		.MCLK(MCLK),
		.c1(c1),
		.c2(c2),
		.data_in(data_in),
		.data_out(data_out)
		);

	wire [DATA_WIDTH-1:0] chain;

	assign data_in = chain | (load ? load_val : {DATA_WIDTH{1'h0}});

	generate
		if (DATA_WIDTH == 1)
			assign chain = prev;
		else
			assign chain = { prev, data_out[DATA_WIDTH-1:1] };
	endgenerate

	assign next = data_out[0];

endmodule

module ym_dbg_read_eg_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input c1,
	input c2,
	input prev,
	input load,
	input [DATA_WIDTH-1:0] load_val,
	output next
	);

	wire [DATA_WIDTH-1:0] data_in;
	wire [DATA_WIDTH-1:0] data_out;

	ym_sr_bit_array_rtl #(.DATA_WIDTH(DATA_WIDTH)) mem
		(
		.MCLK(MCLK),
		.c1(c1),
		.c2(c2),
		.data_in(data_in),
		.data_out(data_out)
		);

	wire [DATA_WIDTH-1:0] chain;

	assign data_in = chain | (load ? load_val : {DATA_WIDTH{1'h0}});

	generate
		if (DATA_WIDTH == 1)
			assign chain = prev;
		else
			assign chain = { data_out[DATA_WIDTH-2:0], prev };
	endgenerate

	assign next = data_out[DATA_WIDTH-1];

endmodule

// transparent latch (c1 phase): mux -> clock enable, exactly equivalent per MCLK
module ym_dlatch_1_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input c1,
	input [DATA_WIDTH-1:0] inp,
	output [DATA_WIDTH-1:0] val,
	output [DATA_WIDTH-1:0] nval
	);

	reg [DATA_WIDTH-1:0] mem = {DATA_WIDTH{1'h0}};

	always @(posedge MCLK)
		if (c1)
			mem <= inp;

	assign val = mem;
	assign nval = ~mem;

endmodule

// transparent latch (c2 phase): mux -> clock enable, exactly equivalent per MCLK
module ym_dlatch_2_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input c2,
	input [DATA_WIDTH-1:0] inp,
	output [DATA_WIDTH-1:0] val,
	output [DATA_WIDTH-1:0] nval
	);

	reg [DATA_WIDTH-1:0] mem = {DATA_WIDTH{1'h0}};

	always @(posedge MCLK)
		if (c2)
			mem <= inp;

	assign val = mem;
	assign nval = ~mem;

endmodule

module ym_edge_detect_rtl
	(
	input MCLK,
	input c1,
	input inp,
	output outp
	);

	wire prev_out;

	ym_dlatch_1_rtl prev
		(
		.MCLK(MCLK),
		.c1(c1),
		.inp(inp),
		.val(prev_out),
		.nval()
		);
	assign outp = ~(prev_out | ~inp);
endmodule

// transparent latch (generic enable): mux -> clock enable, exactly equivalent per MCLK
module ym_slatch_rtl #(parameter DATA_WIDTH = 1)
	(
	input MCLK,
	input en,
	input [DATA_WIDTH-1:0] inp,
	output [DATA_WIDTH-1:0] val,
	output [DATA_WIDTH-1:0] nval
	);

	reg [DATA_WIDTH-1:0] mem = {DATA_WIDTH{1'h0}};

	always @(posedge MCLK)
		if (en)
			mem <= inp;

	assign val = mem;
	assign nval = ~mem;

endmodule

module ym_rs_trig_rtl
	(
	input MCLK,
	input set,
	input rst,
	output reg q = 1'h0,
	output reg nq = 1'h1
	);

	always @(posedge MCLK)
	begin
		q <= rst ? 1'h0 : (set ? 1'h1 : q);
		nq <= set ? 1'h0 : (rst ? 1'h1 : ~q);
	end

endmodule

module ym_rs_trig_sync_rtl
	(
	input MCLK,
	input set,
	input rst,
	input c1,
	output reg q = 1'h0,
	output reg nq = 1'h1
	);

	always @(posedge MCLK)
	begin
		q <= (c1 & rst) ? 1'h0 : ((c1 & set) ? 1'h1 : q);
		nq <= (c1 & set) ? 1'h0 : ((c1 & rst) ? 1'h1 : ~q);
	end

endmodule
