#!/usr/bin/perl
# gen_compare.pl -- generate sim/ym7101/cmp_gen.svh from storage_manifest.txt + plain_signals.txt
# Emits packed die/rtl storage vectors (sto_a/sto_b) and a per-element report task for the A/B bench.
# Manifest rows: label \t die_path \t rtl_path \t width   (paths relative to the DUT instance).
# Plain rows:    name width   (same net name in both die and rtl, prefixed u_die./u_rtl.)
use strict; use warnings;
my $MAN="sim/ym7101/storage_manifest.txt";
my $PLAIN="sim/ym7101/plain_signals.txt";
my $OUT="sim/ym7101/cmp_gen.svh";
my @rows;   # [label, die_expr, rtl_expr, width]
open(my $m,"<",$MAN) or die $!;
while (<$m>){ chomp; next unless /\S/; my ($lab,$dp,$rp,$w)=split /\t/; push @rows,[$lab,"u_die.$dp","u_rtl.$rp",$w]; }
close $m;
open(my $p,"<",$PLAIN) or die $!;
while (<$p>){ chomp; next unless /\S/; my ($n,$w)=split /\s+/; push @rows,["$n","u_die.$n","u_rtl.$n",$w]; }
close $p;
my $W=0; $W+=$_->[3] for @rows;
open(my $o,">",$OUT) or die $!;
print $o "// GENERATED by gen_compare.pl -- do not edit.  ".scalar(@rows)." storage elements, $W bits.\n";
print $o "localparam int STO_W = $W;\n";
print $o "wire [STO_W-1:0] sto_a = {\n";
print $o join(",\n", map { "\t".$_->[1] } @rows), "};\n";
print $o "wire [STO_W-1:0] sto_b = {\n";
print $o join(",\n", map { "\t".$_->[2] } @rows), "};\n";
print $o "task automatic report_storage(input string phase);\n";
for my $r (@rows) {
  (my $lab=$r->[0]) =~ s/"/\\"/g;
  print $o "\t`CMP(\"$lab\", $r->[1], $r->[2])\n";
}
print $o "endtask\n";
close $o;
print STDERR "wrote $OUT: ".scalar(@rows)." elements, $W bits\n";
