#!/usr/bin/perl
# gen_ports.pl -- parse ym7101's port list and emit sim/ym7101/ports_gen.svh:
#   * input declarations (as logic, driven by the TB) except a skip-set the TB drives specially
#   * per-output _a/_b wire pairs
#   * the u_die (ym7101) and u_rtl (ym7101_rtl) instantiations, ports auto-mapped
#   * packed outs_a/outs_b vectors and a report_outputs() task with a CMP per output
use strict; use warnings;
my $SRC="rtl/nuked-md/ym7101.v";
my $OUT="sim/ym7101/ports_gen.svh";
# inputs the TB declares/drives itself (wires via continuous assign, or the clock)
my %SKIP = map {$_=>1} qw(MCLK CLK1_i SD RD_i AD_i);

open(my $f,"<",$SRC) or die $!;
my @lines=<$f>; close $f;
# port list is between "module ym7101" '(' and the closing ');'
my @ports; my $in=0;
for my $l (@lines) {
  if ($l =~ /^\s*module\s+ym7101\s*$/) { $in=1; next; }
  next unless $in;
  last if $l =~ /^\s*\)\s*;/;
  (my $c=$l) =~ s{//.*$}{};
  next unless $c =~ /\b(input|output)\b/;
  # forms: input NAME,  |  input [a:b] NAME,  |  output reg [a:b] NAME,
  if ($c =~ /\b(input|output)\b\s+(?:reg\s+)?(\[[^\]]*\]\s*)?([A-Za-z_]\w*)/) {
    my ($dir,$w,$name)=($1,$2//'',$3);
    $w =~ s/\s+//g;
    push @ports,[$dir,$w,$name];
  }
}
open(my $o,">",$OUT) or die $!;
print $o "// GENERATED by gen_ports.pl -- do not edit.\n";
print $o "// ---- input declarations (TB-driven) ----\n";
for my $p (@ports) {
  next unless $p->[0] eq 'input';
  next if $SKIP{$p->[2]};
  my $w=$p->[1]; print $o "logic ${w}$p->[2] = 0;\n";
}
print $o "// ---- output _a (die) / _b (rtl) pairs ----\n";
for my $p (@ports) {
  next unless $p->[0] eq 'output';
  my $w=$p->[1]; print $o "wire ${w}$p->[2]_a; wire ${w}$p->[2]_b;\n";
}
# instantiations
for my $suf (['u_die','ym7101','_a'],['u_rtl','ym7101_rtl','_b']) {
  my ($inst,$mod,$sfx)=@$suf;
  print $o "$mod $inst (\n";
  my @conn;
  for my $p (@ports) {
    my $n=$p->[2];
    if ($p->[0] eq 'input') { push @conn, "\t.$n($n)"; }
    else { push @conn, "\t.$n($n$sfx)"; }
  }
  print $o join(",\n",@conn), ");\n";
}
# packed outputs + report
my @outs = grep {$_->[0] eq 'output'} @ports;
print $o "wire [".total_out(\@outs)."-1:0] outs_a = {", join(",", map {"$_->[2]_a"} @outs), "};\n";
print $o "wire [".total_out(\@outs)."-1:0] outs_b = {", join(",", map {"$_->[2]_b"} @outs), "};\n";
print $o "task automatic report_outputs(input string phase);\n";
for my $p (@outs) { print $o "\t`CMP(\"$p->[2]\", $p->[2]_a, $p->[2]_b)\n"; }
print $o "endtask\n";
close $o;

sub width_of { my $w=shift; return 1 unless $w; $w=~/\[(\d+):(\d+)\]/ or return 1; return abs($1-$2)+1; }
sub total_out { my $a=shift; my $t=0; $t+=width_of($_->[1]) for @$a; return $t; }
my $ti=0; $ti+=width_of($_->[1]) for @outs;
print STDERR "wrote $OUT: ".scalar(@ports)." ports (".scalar(@outs)." outputs, $ti output bits)\n";
