// GENERATED by gen_ports.pl -- do not edit.
// ---- input declarations (TB-driven) ----
logic SPA_B_i = 0;
logic CSYNC_i = 0;
logic HSYNC_i = 0;
logic HL = 0;
logic SEL0 = 0;
logic PAL = 0;
logic RESET = 0;
logic MCLK_e = 0;
logic EDCLK_i = 0;
logic [15:0]CD_i = 0;
logic [22:0]CA_i = 0;
logic BGACK_i = 0;
logic BG = 0;
logic MREQ = 0;
logic INTAK = 0;
logic IORQ = 0;
logic RD = 0;
logic WR = 0;
logic M1 = 0;
logic AS = 0;
logic UDS = 0;
logic LDS = 0;
logic RW = 0;
logic DTACK_i = 0;
logic ext_test_2 = 0;
logic vdp_cramdot_dis = 0;
// ---- output _a (die) / _b (rtl) pairs ----
wire SE1_a; wire SE1_b;
wire SE0_a; wire SE0_b;
wire SC_a; wire SC_b;
wire RAS1_a; wire RAS1_b;
wire CAS1_a; wire CAS1_b;
wire WE1_a; wire WE1_b;
wire WE0_a; wire WE0_b;
wire OE1_a; wire OE1_b;
wire [7:0]RD_o_a; wire [7:0]RD_o_b;
wire RD_d_a; wire RD_d_b;
wire [7:0]DAC_R_a; wire [7:0]DAC_R_b;
wire [7:0]DAC_G_a; wire [7:0]DAC_G_b;
wire [7:0]DAC_B_a; wire [7:0]DAC_B_b;
wire [7:0]AD_o_a; wire [7:0]AD_o_b;
wire AD_d_a; wire AD_d_b;
wire YS_a; wire YS_b;
wire SPA_B_pull_a; wire SPA_B_pull_b;
wire VSYNC_a; wire VSYNC_b;
wire CSYNC_pull_a; wire CSYNC_pull_b;
wire HSYNC_pull_a; wire HSYNC_pull_b;
wire CLK1_o_a; wire CLK1_o_b;
wire SBCR_a; wire SBCR_b;
wire CLK0_a; wire CLK0_b;
wire EDCLK_o_a; wire EDCLK_o_b;
wire EDCLK_d_a; wire EDCLK_d_b;
wire [15:0]CD_o_a; wire [15:0]CD_o_b;
wire CD_d_a; wire CD_d_b;
wire [22:0]CA_o_a; wire [22:0]CA_o_b;
wire CA_d_a; wire CA_d_b;
wire [15:0]SOUND_a; wire [15:0]SOUND_b;
wire INT_pull_a; wire INT_pull_b;
wire BR_pull_a; wire BR_pull_b;
wire BGACK_pull_a; wire BGACK_pull_b;
wire IPL1_pull_a; wire IPL1_pull_b;
wire IPL2_pull_a; wire IPL2_pull_b;
wire DTACK_pull_a; wire DTACK_pull_b;
wire UWR_a; wire UWR_b;
wire LWR_a; wire LWR_b;
wire OE0_a; wire OE0_b;
wire CAS0_a; wire CAS0_b;
wire RAS0_a; wire RAS0_b;
wire [7:0]RA_a; wire [7:0]RA_b;
wire vdp_hclk1_a; wire vdp_hclk1_b;
wire vdp_intfield_a; wire vdp_intfield_b;
wire vdp_de_h_a; wire vdp_de_h_b;
wire vdp_de_v_a; wire vdp_de_v_b;
wire vdp_m5_a; wire vdp_m5_b;
wire vdp_rs1_a; wire vdp_rs1_b;
wire vdp_m2_a; wire vdp_m2_b;
wire vdp_lcb_a; wire vdp_lcb_b;
wire vdp_psg_clk1_a; wire vdp_psg_clk1_b;
wire vdp_hsync2_a; wire vdp_hsync2_b;
wire vdp_vsync2_a; wire vdp_vsync2_b;
wire vdp_dma_oe_early_a; wire vdp_dma_oe_early_b;
wire vdp_dma_a; wire vdp_dma_b;
ym7101 u_die (
	.MCLK(MCLK),
	.SD(SD),
	.SE1(SE1_a),
	.SE0(SE0_a),
	.SC(SC_a),
	.RAS1(RAS1_a),
	.CAS1(CAS1_a),
	.WE1(WE1_a),
	.WE0(WE0_a),
	.OE1(OE1_a),
	.RD_i(RD_i),
	.RD_o(RD_o_a),
	.RD_d(RD_d_a),
	.DAC_R(DAC_R_a),
	.DAC_G(DAC_G_a),
	.DAC_B(DAC_B_a),
	.AD_i(AD_i),
	.AD_o(AD_o_a),
	.AD_d(AD_d_a),
	.YS(YS_a),
	.SPA_B_i(SPA_B_i),
	.SPA_B_pull(SPA_B_pull_a),
	.VSYNC(VSYNC_a),
	.CSYNC_i(CSYNC_i),
	.CSYNC_pull(CSYNC_pull_a),
	.HSYNC_i(HSYNC_i),
	.HSYNC_pull(HSYNC_pull_a),
	.HL(HL),
	.SEL0(SEL0),
	.PAL(PAL),
	.RESET(RESET),
	.CLK1_i(CLK1_i),
	.CLK1_o(CLK1_o_a),
	.SBCR(SBCR_a),
	.CLK0(CLK0_a),
	.MCLK_e(MCLK_e),
	.EDCLK_i(EDCLK_i),
	.EDCLK_o(EDCLK_o_a),
	.EDCLK_d(EDCLK_d_a),
	.CD_i(CD_i),
	.CD_o(CD_o_a),
	.CD_d(CD_d_a),
	.CA_i(CA_i),
	.CA_o(CA_o_a),
	.CA_d(CA_d_a),
	.SOUND(SOUND_a),
	.INT_pull(INT_pull_a),
	.BR_pull(BR_pull_a),
	.BGACK_i(BGACK_i),
	.BGACK_pull(BGACK_pull_a),
	.BG(BG),
	.MREQ(MREQ),
	.INTAK(INTAK),
	.IPL1_pull(IPL1_pull_a),
	.IPL2_pull(IPL2_pull_a),
	.IORQ(IORQ),
	.RD(RD),
	.WR(WR),
	.M1(M1),
	.AS(AS),
	.UDS(UDS),
	.LDS(LDS),
	.RW(RW),
	.DTACK_i(DTACK_i),
	.DTACK_pull(DTACK_pull_a),
	.UWR(UWR_a),
	.LWR(LWR_a),
	.OE0(OE0_a),
	.CAS0(CAS0_a),
	.RAS0(RAS0_a),
	.RA(RA_a),
	.ext_test_2(ext_test_2),
	.vdp_hclk1(vdp_hclk1_a),
	.vdp_intfield(vdp_intfield_a),
	.vdp_de_h(vdp_de_h_a),
	.vdp_de_v(vdp_de_v_a),
	.vdp_m5(vdp_m5_a),
	.vdp_rs1(vdp_rs1_a),
	.vdp_m2(vdp_m2_a),
	.vdp_lcb(vdp_lcb_a),
	.vdp_psg_clk1(vdp_psg_clk1_a),
	.vdp_hsync2(vdp_hsync2_a),
	.vdp_vsync2(vdp_vsync2_a),
	.vdp_cramdot_dis(vdp_cramdot_dis),
	.vdp_dma_oe_early(vdp_dma_oe_early_a),
	.vdp_dma(vdp_dma_a));
ym7101_rtl u_rtl (
	.MCLK(MCLK),
	.SD(SD),
	.SE1(SE1_b),
	.SE0(SE0_b),
	.SC(SC_b),
	.RAS1(RAS1_b),
	.CAS1(CAS1_b),
	.WE1(WE1_b),
	.WE0(WE0_b),
	.OE1(OE1_b),
	.RD_i(RD_i),
	.RD_o(RD_o_b),
	.RD_d(RD_d_b),
	.DAC_R(DAC_R_b),
	.DAC_G(DAC_G_b),
	.DAC_B(DAC_B_b),
	.AD_i(AD_i),
	.AD_o(AD_o_b),
	.AD_d(AD_d_b),
	.YS(YS_b),
	.SPA_B_i(SPA_B_i),
	.SPA_B_pull(SPA_B_pull_b),
	.VSYNC(VSYNC_b),
	.CSYNC_i(CSYNC_i),
	.CSYNC_pull(CSYNC_pull_b),
	.HSYNC_i(HSYNC_i),
	.HSYNC_pull(HSYNC_pull_b),
	.HL(HL),
	.SEL0(SEL0),
	.PAL(PAL),
	.RESET(RESET),
	.CLK1_i(CLK1_i),
	.CLK1_o(CLK1_o_b),
	.SBCR(SBCR_b),
	.CLK0(CLK0_b),
	.MCLK_e(MCLK_e),
	.EDCLK_i(EDCLK_i),
	.EDCLK_o(EDCLK_o_b),
	.EDCLK_d(EDCLK_d_b),
	.CD_i(CD_i),
	.CD_o(CD_o_b),
	.CD_d(CD_d_b),
	.CA_i(CA_i),
	.CA_o(CA_o_b),
	.CA_d(CA_d_b),
	.SOUND(SOUND_b),
	.INT_pull(INT_pull_b),
	.BR_pull(BR_pull_b),
	.BGACK_i(BGACK_i),
	.BGACK_pull(BGACK_pull_b),
	.BG(BG),
	.MREQ(MREQ),
	.INTAK(INTAK),
	.IPL1_pull(IPL1_pull_b),
	.IPL2_pull(IPL2_pull_b),
	.IORQ(IORQ),
	.RD(RD),
	.WR(WR),
	.M1(M1),
	.AS(AS),
	.UDS(UDS),
	.LDS(LDS),
	.RW(RW),
	.DTACK_i(DTACK_i),
	.DTACK_pull(DTACK_pull_b),
	.UWR(UWR_b),
	.LWR(LWR_b),
	.OE0(OE0_b),
	.CAS0(CAS0_b),
	.RAS0(RAS0_b),
	.RA(RA_b),
	.ext_test_2(ext_test_2),
	.vdp_hclk1(vdp_hclk1_b),
	.vdp_intfield(vdp_intfield_b),
	.vdp_de_h(vdp_de_h_b),
	.vdp_de_v(vdp_de_v_b),
	.vdp_m5(vdp_m5_b),
	.vdp_rs1(vdp_rs1_b),
	.vdp_m2(vdp_m2_b),
	.vdp_lcb(vdp_lcb_b),
	.vdp_psg_clk1(vdp_psg_clk1_b),
	.vdp_hsync2(vdp_hsync2_b),
	.vdp_vsync2(vdp_vsync2_b),
	.vdp_cramdot_dis(vdp_cramdot_dis),
	.vdp_dma_oe_early(vdp_dma_oe_early_b),
	.vdp_dma(vdp_dma_b));
wire [149-1:0] outs_a = {SE1_a,SE0_a,SC_a,RAS1_a,CAS1_a,WE1_a,WE0_a,OE1_a,RD_o_a,RD_d_a,DAC_R_a,DAC_G_a,DAC_B_a,AD_o_a,AD_d_a,YS_a,SPA_B_pull_a,VSYNC_a,CSYNC_pull_a,HSYNC_pull_a,CLK1_o_a,SBCR_a,CLK0_a,EDCLK_o_a,EDCLK_d_a,CD_o_a,CD_d_a,CA_o_a,CA_d_a,SOUND_a,INT_pull_a,BR_pull_a,BGACK_pull_a,IPL1_pull_a,IPL2_pull_a,DTACK_pull_a,UWR_a,LWR_a,OE0_a,CAS0_a,RAS0_a,RA_a,vdp_hclk1_a,vdp_intfield_a,vdp_de_h_a,vdp_de_v_a,vdp_m5_a,vdp_rs1_a,vdp_m2_a,vdp_lcb_a,vdp_psg_clk1_a,vdp_hsync2_a,vdp_vsync2_a,vdp_dma_oe_early_a,vdp_dma_a};
wire [149-1:0] outs_b = {SE1_b,SE0_b,SC_b,RAS1_b,CAS1_b,WE1_b,WE0_b,OE1_b,RD_o_b,RD_d_b,DAC_R_b,DAC_G_b,DAC_B_b,AD_o_b,AD_d_b,YS_b,SPA_B_pull_b,VSYNC_b,CSYNC_pull_b,HSYNC_pull_b,CLK1_o_b,SBCR_b,CLK0_b,EDCLK_o_b,EDCLK_d_b,CD_o_b,CD_d_b,CA_o_b,CA_d_b,SOUND_b,INT_pull_b,BR_pull_b,BGACK_pull_b,IPL1_pull_b,IPL2_pull_b,DTACK_pull_b,UWR_b,LWR_b,OE0_b,CAS0_b,RAS0_b,RA_b,vdp_hclk1_b,vdp_intfield_b,vdp_de_h_b,vdp_de_v_b,vdp_m5_b,vdp_rs1_b,vdp_m2_b,vdp_lcb_b,vdp_psg_clk1_b,vdp_hsync2_b,vdp_vsync2_b,vdp_dma_oe_early_b,vdp_dma_b};
task automatic report_outputs(input string phase);
	`CMP("SE1", SE1_a, SE1_b)
	`CMP("SE0", SE0_a, SE0_b)
	`CMP("SC", SC_a, SC_b)
	`CMP("RAS1", RAS1_a, RAS1_b)
	`CMP("CAS1", CAS1_a, CAS1_b)
	`CMP("WE1", WE1_a, WE1_b)
	`CMP("WE0", WE0_a, WE0_b)
	`CMP("OE1", OE1_a, OE1_b)
	`CMP("RD_o", RD_o_a, RD_o_b)
	`CMP("RD_d", RD_d_a, RD_d_b)
	`CMP("DAC_R", DAC_R_a, DAC_R_b)
	`CMP("DAC_G", DAC_G_a, DAC_G_b)
	`CMP("DAC_B", DAC_B_a, DAC_B_b)
	`CMP("AD_o", AD_o_a, AD_o_b)
	`CMP("AD_d", AD_d_a, AD_d_b)
	`CMP("YS", YS_a, YS_b)
	`CMP("SPA_B_pull", SPA_B_pull_a, SPA_B_pull_b)
	`CMP("VSYNC", VSYNC_a, VSYNC_b)
	`CMP("CSYNC_pull", CSYNC_pull_a, CSYNC_pull_b)
	`CMP("HSYNC_pull", HSYNC_pull_a, HSYNC_pull_b)
	`CMP("CLK1_o", CLK1_o_a, CLK1_o_b)
	`CMP("SBCR", SBCR_a, SBCR_b)
	`CMP("CLK0", CLK0_a, CLK0_b)
	`CMP("EDCLK_o", EDCLK_o_a, EDCLK_o_b)
	`CMP("EDCLK_d", EDCLK_d_a, EDCLK_d_b)
	`CMP("CD_o", CD_o_a, CD_o_b)
	`CMP("CD_d", CD_d_a, CD_d_b)
	`CMP("CA_o", CA_o_a, CA_o_b)
	`CMP("CA_d", CA_d_a, CA_d_b)
	`CMP("SOUND", SOUND_a, SOUND_b)
	`CMP("INT_pull", INT_pull_a, INT_pull_b)
	`CMP("BR_pull", BR_pull_a, BR_pull_b)
	`CMP("BGACK_pull", BGACK_pull_a, BGACK_pull_b)
	`CMP("IPL1_pull", IPL1_pull_a, IPL1_pull_b)
	`CMP("IPL2_pull", IPL2_pull_a, IPL2_pull_b)
	`CMP("DTACK_pull", DTACK_pull_a, DTACK_pull_b)
	`CMP("UWR", UWR_a, UWR_b)
	`CMP("LWR", LWR_a, LWR_b)
	`CMP("OE0", OE0_a, OE0_b)
	`CMP("CAS0", CAS0_a, CAS0_b)
	`CMP("RAS0", RAS0_a, RAS0_b)
	`CMP("RA", RA_a, RA_b)
	`CMP("vdp_hclk1", vdp_hclk1_a, vdp_hclk1_b)
	`CMP("vdp_intfield", vdp_intfield_a, vdp_intfield_b)
	`CMP("vdp_de_h", vdp_de_h_a, vdp_de_h_b)
	`CMP("vdp_de_v", vdp_de_v_a, vdp_de_v_b)
	`CMP("vdp_m5", vdp_m5_a, vdp_m5_b)
	`CMP("vdp_rs1", vdp_rs1_a, vdp_rs1_b)
	`CMP("vdp_m2", vdp_m2_a, vdp_m2_b)
	`CMP("vdp_lcb", vdp_lcb_a, vdp_lcb_b)
	`CMP("vdp_psg_clk1", vdp_psg_clk1_a, vdp_psg_clk1_b)
	`CMP("vdp_hsync2", vdp_hsync2_a, vdp_hsync2_b)
	`CMP("vdp_vsync2", vdp_vsync2_a, vdp_vsync2_b)
	`CMP("vdp_dma_oe_early", vdp_dma_oe_early_a, vdp_dma_oe_early_b)
	`CMP("vdp_dma", vdp_dma_a, vdp_dma_b)
endtask
